/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateAChannelMetadataResponse model module.
 * @module model/CreateAChannelMetadataResponse
 * @version 2.1.2
 */
class CreateAChannelMetadataResponse {
    /**
     * Constructs a new <code>CreateAChannelMetadataResponse</code>.
     * @alias module:model/CreateAChannelMetadataResponse
     */
    constructor() { 
        
        CreateAChannelMetadataResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateAChannelMetadataResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAChannelMetadataResponse} obj Optional instance to populate.
     * @return {module:model/CreateAChannelMetadataResponse} The populated <code>CreateAChannelMetadataResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAChannelMetadataResponse();

            if (data.hasOwnProperty('include_ts')) {
                obj['include_ts'] = ApiClient.convertToType(data['include_ts'], 'Number');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} include_ts
 */
CreateAChannelMetadataResponse.prototype['include_ts'] = undefined;

/**
 * @member {Object} metadata
 */
CreateAChannelMetadataResponse.prototype['metadata'] = undefined;






export default CreateAChannelMetadataResponse;

