/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2004Template from './InlineResponse2004Template';

/**
 * The InlineResponse20015PushMessageTemplates model module.
 * @module model/InlineResponse20015PushMessageTemplates
 * @version 1.0.0
 */
class InlineResponse20015PushMessageTemplates {
    /**
     * Constructs a new <code>InlineResponse20015PushMessageTemplates</code>.
     * @alias module:model/InlineResponse20015PushMessageTemplates
     */
    constructor() { 
        
        InlineResponse20015PushMessageTemplates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20015PushMessageTemplates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20015PushMessageTemplates} obj Optional instance to populate.
     * @return {module:model/InlineResponse20015PushMessageTemplates} The populated <code>InlineResponse20015PushMessageTemplates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20015PushMessageTemplates();

            if (data.hasOwnProperty('template_name')) {
                obj['template_name'] = ApiClient.convertToType(data['template_name'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = InlineResponse2004Template.constructFromObject(data['template']);
            }
            if (data.hasOwnProperty('push_message_preview')) {
                obj['push_message_preview'] = InlineResponse2004Template.constructFromObject(data['push_message_preview']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} template_name
 */
InlineResponse20015PushMessageTemplates.prototype['template_name'] = undefined;

/**
 * @member {module:model/InlineResponse2004Template} template
 */
InlineResponse20015PushMessageTemplates.prototype['template'] = undefined;

/**
 * @member {module:model/InlineResponse2004Template} push_message_preview
 */
InlineResponse20015PushMessageTemplates.prototype['push_message_preview'] = undefined;






export default InlineResponse20015PushMessageTemplates;

