/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20068Webhook from './InlineResponse20068Webhook';

/**
 * The InlineResponse20068 model module.
 * @module model/InlineResponse20068
 * @version 1.0.0
 */
class InlineResponse20068 {
    /**
     * Constructs a new <code>InlineResponse20068</code>.
     * @alias module:model/InlineResponse20068
     */
    constructor() { 
        
        InlineResponse20068.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20068</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20068} obj Optional instance to populate.
     * @return {module:model/InlineResponse20068} The populated <code>InlineResponse20068</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20068();

            if (data.hasOwnProperty('webhook')) {
                obj['webhook'] = InlineResponse20068Webhook.constructFromObject(data['webhook']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse20068Webhook} webhook
 */
InlineResponse20068.prototype['webhook'] = undefined;






export default InlineResponse20068;

