/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20048OgTagOgImage model module.
 * @module model/InlineResponse20048OgTagOgImage
 * @version 1.0.0
 */
class InlineResponse20048OgTagOgImage {
    /**
     * Constructs a new <code>InlineResponse20048OgTagOgImage</code>.
     * @alias module:model/InlineResponse20048OgTagOgImage
     */
    constructor() { 
        
        InlineResponse20048OgTagOgImage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20048OgTagOgImage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20048OgTagOgImage} obj Optional instance to populate.
     * @return {module:model/InlineResponse20048OgTagOgImage} The populated <code>InlineResponse20048OgTagOgImage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20048OgTagOgImage();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('secure_url')) {
                obj['secure_url'] = ApiClient.convertToType(data['secure_url'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
InlineResponse20048OgTagOgImage.prototype['url'] = undefined;

/**
 * @member {String} secure_url
 */
InlineResponse20048OgTagOgImage.prototype['secure_url'] = undefined;

/**
 * @member {Number} width
 */
InlineResponse20048OgTagOgImage.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
InlineResponse20048OgTagOgImage.prototype['height'] = undefined;






export default InlineResponse20048OgTagOgImage;

