/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20041Message from './InlineResponse20041Message';

/**
 * The InlineResponse20041 model module.
 * @module model/InlineResponse20041
 * @version 1.0.0
 */
class InlineResponse20041 {
    /**
     * Constructs a new <code>InlineResponse20041</code>.
     * @alias module:model/InlineResponse20041
     */
    constructor() { 
        
        InlineResponse20041.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20041</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20041} obj Optional instance to populate.
     * @return {module:model/InlineResponse20041} The populated <code>InlineResponse20041</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20041();

            if (data.hasOwnProperty('unique_id')) {
                obj['unique_id'] = ApiClient.convertToType(data['unique_id'], 'String');
            }
            if (data.hasOwnProperty('announcement_group')) {
                obj['announcement_group'] = ApiClient.convertToType(data['announcement_group'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = InlineResponse20041Message.constructFromObject(data['message']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} unique_id
 */
InlineResponse20041.prototype['unique_id'] = undefined;

/**
 * @member {String} announcement_group
 */
InlineResponse20041.prototype['announcement_group'] = undefined;

/**
 * @member {module:model/InlineResponse20041Message} message
 */
InlineResponse20041.prototype['message'] = undefined;






export default InlineResponse20041;

