/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MarkAllMessagesAsReadRequest model module.
 * @module model/MarkAllMessagesAsReadRequest
 * @version 2.1.2
 */
class MarkAllMessagesAsReadRequest {
    /**
     * Constructs a new <code>MarkAllMessagesAsReadRequest</code>.
     * @alias module:model/MarkAllMessagesAsReadRequest
     */
    constructor() { 
        
        MarkAllMessagesAsReadRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MarkAllMessagesAsReadRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MarkAllMessagesAsReadRequest} obj Optional instance to populate.
     * @return {module:model/MarkAllMessagesAsReadRequest} The populated <code>MarkAllMessagesAsReadRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarkAllMessagesAsReadRequest();

            if (data.hasOwnProperty('channel_urls')) {
                obj['channel_urls'] = ApiClient.convertToType(data['channel_urls'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Specifies an array of one or more group channel URLs where unread messages need to be marked as read. If not specified, unread messages in all group channels a user joined are marked as read.
 * @member {Array.<String>} channel_urls
 */
MarkAllMessagesAsReadRequest.prototype['channel_urls'] = undefined;






export default MarkAllMessagesAsReadRequest;

