/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScheduleAnAnnouncementRequestMessage model module.
 * @module model/ScheduleAnAnnouncementRequestMessage
 * @version 2.0.0
 */
class ScheduleAnAnnouncementRequestMessage {
    /**
     * Constructs a new <code>ScheduleAnAnnouncementRequestMessage</code>.
     * @alias module:model/ScheduleAnAnnouncementRequestMessage
     */
    constructor() { 
        
        ScheduleAnAnnouncementRequestMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScheduleAnAnnouncementRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleAnAnnouncementRequestMessage} obj Optional instance to populate.
     * @return {module:model/ScheduleAnAnnouncementRequestMessage} The populated <code>ScheduleAnAnnouncementRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleAnAnnouncementRequestMessage();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('custom_type')) {
                obj['custom_type'] = ApiClient.convertToType(data['custom_type'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} content
 */
ScheduleAnAnnouncementRequestMessage.prototype['content'] = undefined;

/**
 * @member {String} custom_type
 */
ScheduleAnAnnouncementRequestMessage.prototype['custom_type'] = undefined;

/**
 * @member {String} data
 */
ScheduleAnAnnouncementRequestMessage.prototype['data'] = undefined;

/**
 * @member {String} type
 */
ScheduleAnAnnouncementRequestMessage.prototype['type'] = undefined;

/**
 * @member {String} user_id
 */
ScheduleAnAnnouncementRequestMessage.prototype['user_id'] = undefined;






export default ScheduleAnAnnouncementRequestMessage;

