/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScheduleAnAnnouncementRequestCreateChannelOptions from './ScheduleAnAnnouncementRequestCreateChannelOptions';
import ScheduleAnAnnouncementRequestMessage from './ScheduleAnAnnouncementRequestMessage';

/**
 * The ScheduleAnAnnouncementRequest model module.
 * @module model/ScheduleAnAnnouncementRequest
 * @version 2.1.1
 */
class ScheduleAnAnnouncementRequest {
    /**
     * Constructs a new <code>ScheduleAnAnnouncementRequest</code>.
     * @alias module:model/ScheduleAnAnnouncementRequest
     */
    constructor() { 
        
        ScheduleAnAnnouncementRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScheduleAnAnnouncementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleAnAnnouncementRequest} obj Optional instance to populate.
     * @return {module:model/ScheduleAnAnnouncementRequest} The populated <code>ScheduleAnAnnouncementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleAnAnnouncementRequest();

            if (data.hasOwnProperty('announcement_group')) {
                obj['announcement_group'] = ApiClient.convertToType(data['announcement_group'], 'String');
            }
            if (data.hasOwnProperty('assign_sender_as_channel_inviter')) {
                obj['assign_sender_as_channel_inviter'] = ApiClient.convertToType(data['assign_sender_as_channel_inviter'], 'Boolean');
            }
            if (data.hasOwnProperty('cease_at')) {
                obj['cease_at'] = ApiClient.convertToType(data['cease_at'], 'String');
            }
            if (data.hasOwnProperty('create_channel')) {
                obj['create_channel'] = ApiClient.convertToType(data['create_channel'], 'Boolean');
            }
            if (data.hasOwnProperty('create_channel_options')) {
                obj['create_channel_options'] = ScheduleAnAnnouncementRequestCreateChannelOptions.constructFromObject(data['create_channel_options']);
            }
            if (data.hasOwnProperty('enable_push')) {
                obj['enable_push'] = ApiClient.convertToType(data['enable_push'], 'Boolean');
            }
            if (data.hasOwnProperty('end_at')) {
                obj['end_at'] = ApiClient.convertToType(data['end_at'], 'Number');
            }
            if (data.hasOwnProperty('keep_channel_hidden_for_sender')) {
                obj['keep_channel_hidden_for_sender'] = ApiClient.convertToType(data['keep_channel_hidden_for_sender'], 'Boolean');
            }
            if (data.hasOwnProperty('mark_as_read')) {
                obj['mark_as_read'] = ApiClient.convertToType(data['mark_as_read'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ScheduleAnAnnouncementRequestMessage.constructFromObject(data['message']);
            }
            if (data.hasOwnProperty('resume_at')) {
                obj['resume_at'] = ApiClient.convertToType(data['resume_at'], 'String');
            }
            if (data.hasOwnProperty('scheduled_at')) {
                obj['scheduled_at'] = ApiClient.convertToType(data['scheduled_at'], 'Number');
            }
            if (data.hasOwnProperty('send_to_frozen_channels')) {
                obj['send_to_frozen_channels'] = ApiClient.convertToType(data['send_to_frozen_channels'], 'Boolean');
            }
            if (data.hasOwnProperty('target_at')) {
                obj['target_at'] = ApiClient.convertToType(data['target_at'], 'String');
            }
            if (data.hasOwnProperty('target_channel_type')) {
                obj['target_channel_type'] = ApiClient.convertToType(data['target_channel_type'], 'String');
            }
            if (data.hasOwnProperty('target_custom_type')) {
                obj['target_custom_type'] = ApiClient.convertToType(data['target_custom_type'], 'String');
            }
            if (data.hasOwnProperty('target_list')) {
                obj['target_list'] = ApiClient.convertToType(data['target_list'], ['String']);
            }
            if (data.hasOwnProperty('unique_id')) {
                obj['unique_id'] = ApiClient.convertToType(data['unique_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} announcement_group
 */
ScheduleAnAnnouncementRequest.prototype['announcement_group'] = undefined;

/**
 * @member {Boolean} assign_sender_as_channel_inviter
 */
ScheduleAnAnnouncementRequest.prototype['assign_sender_as_channel_inviter'] = undefined;

/**
 * @member {String} cease_at
 */
ScheduleAnAnnouncementRequest.prototype['cease_at'] = undefined;

/**
 * @member {Boolean} create_channel
 */
ScheduleAnAnnouncementRequest.prototype['create_channel'] = undefined;

/**
 * @member {module:model/ScheduleAnAnnouncementRequestCreateChannelOptions} create_channel_options
 */
ScheduleAnAnnouncementRequest.prototype['create_channel_options'] = undefined;

/**
 * @member {Boolean} enable_push
 */
ScheduleAnAnnouncementRequest.prototype['enable_push'] = undefined;

/**
 * @member {Number} end_at
 */
ScheduleAnAnnouncementRequest.prototype['end_at'] = undefined;

/**
 * @member {Boolean} keep_channel_hidden_for_sender
 */
ScheduleAnAnnouncementRequest.prototype['keep_channel_hidden_for_sender'] = undefined;

/**
 * @member {Boolean} mark_as_read
 */
ScheduleAnAnnouncementRequest.prototype['mark_as_read'] = undefined;

/**
 * @member {module:model/ScheduleAnAnnouncementRequestMessage} message
 */
ScheduleAnAnnouncementRequest.prototype['message'] = undefined;

/**
 * @member {String} resume_at
 */
ScheduleAnAnnouncementRequest.prototype['resume_at'] = undefined;

/**
 * @member {Number} scheduled_at
 */
ScheduleAnAnnouncementRequest.prototype['scheduled_at'] = undefined;

/**
 * @member {Boolean} send_to_frozen_channels
 */
ScheduleAnAnnouncementRequest.prototype['send_to_frozen_channels'] = undefined;

/**
 * @member {String} target_at
 */
ScheduleAnAnnouncementRequest.prototype['target_at'] = undefined;

/**
 * @member {String} target_channel_type
 */
ScheduleAnAnnouncementRequest.prototype['target_channel_type'] = undefined;

/**
 * @member {String} target_custom_type
 */
ScheduleAnAnnouncementRequest.prototype['target_custom_type'] = undefined;

/**
 * @member {Array.<String>} target_list
 */
ScheduleAnAnnouncementRequest.prototype['target_list'] = undefined;

/**
 * @member {String} unique_id
 */
ScheduleAnAnnouncementRequest.prototype['unique_id'] = undefined;






export default ScheduleAnAnnouncementRequest;

