/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendBirdSearchField model module.
 * @module model/SendBirdSearchField
 * @version 1.0.0
 */
class SendBirdSearchField {
    /**
     * Constructs a new <code>SendBirdSearchField</code>.
     * @alias module:model/SendBirdSearchField
     */
    constructor() { 
        
        SendBirdSearchField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdSearchField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdSearchField} obj Optional instance to populate.
     * @return {module:model/SendBirdSearchField} The populated <code>SendBirdSearchField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdSearchField();

            if (data.hasOwnProperty('CHANNEL_NAME')) {
                obj['CHANNEL_NAME'] = ApiClient.convertToType(data['CHANNEL_NAME'], 'String');
            }
            if (data.hasOwnProperty('MEMBER_NICKNAME')) {
                obj['MEMBER_NICKNAME'] = ApiClient.convertToType(data['MEMBER_NICKNAME'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdSearchField.CHANNELNAMEEnum} CHANNEL_NAME
 */
SendBirdSearchField.prototype['CHANNEL_NAME'] = undefined;

/**
 * @member {module:model/SendBirdSearchField.MEMBERNICKNAMEEnum} MEMBER_NICKNAME
 */
SendBirdSearchField.prototype['MEMBER_NICKNAME'] = undefined;





/**
 * Allowed values for the <code>CHANNEL_NAME</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdSearchField['CHANNELNAMEEnum'] = {

    /**
     * value: "channel_name"
     * @const
     */
    "channel_name": "channel_name"
};


/**
 * Allowed values for the <code>MEMBER_NICKNAME</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdSearchField['MEMBERNICKNAMEEnum'] = {

    /**
     * value: "member_nickname"
     * @const
     */
    "member_nickname": "member_nickname"
};



export default SendBirdSearchField;

