/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendBirdMessageRetrievalParams model module.
 * @module model/SendBirdMessageRetrievalParams
 * @version 1.0.0
 */
class SendBirdMessageRetrievalParams {
    /**
     * Constructs a new <code>SendBirdMessageRetrievalParams</code>.
     * @alias module:model/SendBirdMessageRetrievalParams
     */
    constructor() { 
        
        SendBirdMessageRetrievalParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdMessageRetrievalParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdMessageRetrievalParams} obj Optional instance to populate.
     * @return {module:model/SendBirdMessageRetrievalParams} The populated <code>SendBirdMessageRetrievalParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdMessageRetrievalParams();

            if (data.hasOwnProperty('channelType')) {
                obj['channelType'] = ApiClient.convertToType(data['channelType'], 'String');
            }
            if (data.hasOwnProperty('channelUrl')) {
                obj['channelUrl'] = ApiClient.convertToType(data['channelUrl'], 'String');
            }
            if (data.hasOwnProperty('includeMetaArray')) {
                obj['includeMetaArray'] = ApiClient.convertToType(data['includeMetaArray'], 'Boolean');
            }
            if (data.hasOwnProperty('includeParentMessageInfo')) {
                obj['includeParentMessageInfo'] = ApiClient.convertToType(data['includeParentMessageInfo'], 'Boolean');
            }
            if (data.hasOwnProperty('includeParentMessageText')) {
                obj['includeParentMessageText'] = ApiClient.convertToType(data['includeParentMessageText'], 'Boolean');
            }
            if (data.hasOwnProperty('includePollDetails')) {
                obj['includePollDetails'] = ApiClient.convertToType(data['includePollDetails'], 'Boolean');
            }
            if (data.hasOwnProperty('includeReactions')) {
                obj['includeReactions'] = ApiClient.convertToType(data['includeReactions'], 'Boolean');
            }
            if (data.hasOwnProperty('includeThreadInfo')) {
                obj['includeThreadInfo'] = ApiClient.convertToType(data['includeThreadInfo'], 'Boolean');
            }
            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} channelType
 */
SendBirdMessageRetrievalParams.prototype['channelType'] = undefined;

/**
 * @member {String} channelUrl
 */
SendBirdMessageRetrievalParams.prototype['channelUrl'] = undefined;

/**
 * @member {Boolean} includeMetaArray
 */
SendBirdMessageRetrievalParams.prototype['includeMetaArray'] = undefined;

/**
 * @member {Boolean} includeParentMessageInfo
 */
SendBirdMessageRetrievalParams.prototype['includeParentMessageInfo'] = undefined;

/**
 * @member {Boolean} includeParentMessageText
 */
SendBirdMessageRetrievalParams.prototype['includeParentMessageText'] = undefined;

/**
 * @member {Boolean} includePollDetails
 */
SendBirdMessageRetrievalParams.prototype['includePollDetails'] = undefined;

/**
 * @member {Boolean} includeReactions
 */
SendBirdMessageRetrievalParams.prototype['includeReactions'] = undefined;

/**
 * @member {Boolean} includeThreadInfo
 */
SendBirdMessageRetrievalParams.prototype['includeThreadInfo'] = undefined;

/**
 * @member {Number} messageId
 */
SendBirdMessageRetrievalParams.prototype['messageId'] = undefined;






export default SendBirdMessageRetrievalParams;

