/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendBirdSendBirdInstanceBaseChannelMessageTypeFilter from './SendBirdSendBirdInstanceBaseChannelMessageTypeFilter';

/**
 * The SendBirdSendBirdInstanceBaseChannel model module.
 * @module model/SendBirdSendBirdInstanceBaseChannel
 * @version 1.0.0
 */
class SendBirdSendBirdInstanceBaseChannel {
    /**
     * Constructs a new <code>SendBirdSendBirdInstanceBaseChannel</code>.
     * @alias module:model/SendBirdSendBirdInstanceBaseChannel
     */
    constructor() { 
        
        SendBirdSendBirdInstanceBaseChannel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdSendBirdInstanceBaseChannel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdSendBirdInstanceBaseChannel} obj Optional instance to populate.
     * @return {module:model/SendBirdSendBirdInstanceBaseChannel} The populated <code>SendBirdSendBirdInstanceBaseChannel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdSendBirdInstanceBaseChannel();

            if (data.hasOwnProperty('MessageTypeFilter')) {
                obj['MessageTypeFilter'] = SendBirdSendBirdInstanceBaseChannelMessageTypeFilter.constructFromObject(data['MessageTypeFilter']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdSendBirdInstanceBaseChannelMessageTypeFilter} MessageTypeFilter
 */
SendBirdSendBirdInstanceBaseChannel.prototype['MessageTypeFilter'] = undefined;






export default SendBirdSendBirdInstanceBaseChannel;

