/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendBirdRestrictedUserStaticRestrictionType model module.
 * @module model/SendBirdRestrictedUserStaticRestrictionType
 * @version 1.0.0
 */
class SendBirdRestrictedUserStaticRestrictionType {
    /**
     * Constructs a new <code>SendBirdRestrictedUserStaticRestrictionType</code>.
     * @alias module:model/SendBirdRestrictedUserStaticRestrictionType
     */
    constructor() { 
        
        SendBirdRestrictedUserStaticRestrictionType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdRestrictedUserStaticRestrictionType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdRestrictedUserStaticRestrictionType} obj Optional instance to populate.
     * @return {module:model/SendBirdRestrictedUserStaticRestrictionType} The populated <code>SendBirdRestrictedUserStaticRestrictionType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdRestrictedUserStaticRestrictionType();

            if (data.hasOwnProperty('BANNED')) {
                obj['BANNED'] = ApiClient.convertToType(data['BANNED'], 'String');
            }
            if (data.hasOwnProperty('MUTED')) {
                obj['MUTED'] = ApiClient.convertToType(data['MUTED'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdRestrictedUserStaticRestrictionType.BANNEDEnum} BANNED
 */
SendBirdRestrictedUserStaticRestrictionType.prototype['BANNED'] = undefined;

/**
 * @member {module:model/SendBirdRestrictedUserStaticRestrictionType.MUTEDEnum} MUTED
 */
SendBirdRestrictedUserStaticRestrictionType.prototype['MUTED'] = undefined;





/**
 * Allowed values for the <code>BANNED</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdRestrictedUserStaticRestrictionType['BANNEDEnum'] = {

    /**
     * value: "banned"
     * @const
     */
    "banned": "banned"
};


/**
 * Allowed values for the <code>MUTED</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdRestrictedUserStaticRestrictionType['MUTEDEnum'] = {

    /**
     * value: "muted"
     * @const
     */
    "muted": "muted"
};



export default SendBirdRestrictedUserStaticRestrictionType;

