/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendbirdBasicUserInfo model module.
 * @module model/SendbirdBasicUserInfo
 * @version 2.1.1
 */
class SendbirdBasicUserInfo {
    /**
     * Constructs a new <code>SendbirdBasicUserInfo</code>.
     * @alias module:model/SendbirdBasicUserInfo
     * @param userId {String} 
     */
    constructor(userId) { 
        
        SendbirdBasicUserInfo.initialize(this, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId) { 
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>SendbirdBasicUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendbirdBasicUserInfo} obj Optional instance to populate.
     * @return {module:model/SendbirdBasicUserInfo} The populated <code>SendbirdBasicUserInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendbirdBasicUserInfo();

            if (data.hasOwnProperty('require_auth_for_profile_image')) {
                obj['require_auth_for_profile_image'] = ApiClient.convertToType(data['require_auth_for_profile_image'], 'Boolean');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('is_blocked_by_me')) {
                obj['is_blocked_by_me'] = ApiClient.convertToType(data['is_blocked_by_me'], 'Boolean');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('profile_url')) {
                obj['profile_url'] = ApiClient.convertToType(data['profile_url'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} require_auth_for_profile_image
 */
SendbirdBasicUserInfo.prototype['require_auth_for_profile_image'] = undefined;

/**
 * @member {Boolean} is_active
 */
SendbirdBasicUserInfo.prototype['is_active'] = undefined;

/**
 * @member {Boolean} is_blocked_by_me
 */
SendbirdBasicUserInfo.prototype['is_blocked_by_me'] = undefined;

/**
 * @member {module:model/SendbirdBasicUserInfo.RoleEnum} role
 */
SendbirdBasicUserInfo.prototype['role'] = undefined;

/**
 * @member {String} nickname
 */
SendbirdBasicUserInfo.prototype['nickname'] = undefined;

/**
 * @member {String} user_id
 */
SendbirdBasicUserInfo.prototype['user_id'] = undefined;

/**
 * @member {String} profile_url
 */
SendbirdBasicUserInfo.prototype['profile_url'] = undefined;

/**
 * @member {Object} metadata
 */
SendbirdBasicUserInfo.prototype['metadata'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
SendbirdBasicUserInfo['RoleEnum'] = {

    /**
     * value: ""
     * @const
     */
    "empty": "",

    /**
     * value: "none"
     * @const
     */
    "none": "none",

    /**
     * value: "operator"
     * @const
     */
    "operator": "operator"
};



export default SendbirdBasicUserInfo;

