/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
 * The SendBirdUser model module.
 * @module model/SendBirdUser
 * @version 1.0.0
 */
class SendBirdUser {
    /**
     * Constructs a new <code>SendBirdUser</code>.
     * User
     * @alias module:model/SendBirdUser
     */
    constructor() { 
        
        SendBirdUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdUser} obj Optional instance to populate.
     * @return {module:model/SendBirdUser} The populated <code>SendBirdUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdUser();

            if (data.hasOwnProperty('connectionStatus')) {
                obj['connectionStatus'] = ApiClient.convertToType(data['connectionStatus'], 'String');
            }
            if (data.hasOwnProperty('friendDiscoveryKey')) {
                obj['friendDiscoveryKey'] = ApiClient.convertToType(data['friendDiscoveryKey'], 'String');
            }
            if (data.hasOwnProperty('friendName')) {
                obj['friendName'] = ApiClient.convertToType(data['friendName'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('lastSeenAt')) {
                obj['lastSeenAt'] = ApiClient.convertToType(data['lastSeenAt'], 'String');
            }
            if (data.hasOwnProperty('metaData')) {
                obj['metaData'] = ModelObject.constructFromObject(data['metaData']);
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('plainProfileUrl')) {
                obj['plainProfileUrl'] = ApiClient.convertToType(data['plainProfileUrl'], 'String');
            }
            if (data.hasOwnProperty('preferredLanguages')) {
                obj['preferredLanguages'] = ApiClient.convertToType(data['preferredLanguages'], ['String']);
            }
            if (data.hasOwnProperty('profileUrl')) {
                obj['profileUrl'] = ApiClient.convertToType(data['profileUrl'], 'String');
            }
            if (data.hasOwnProperty('requireAuth')) {
                obj['requireAuth'] = ApiClient.convertToType(data['requireAuth'], 'Boolean');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} connectionStatus
 */
SendBirdUser.prototype['connectionStatus'] = undefined;

/**
 * @member {String} friendDiscoveryKey
 */
SendBirdUser.prototype['friendDiscoveryKey'] = undefined;

/**
 * @member {String} friendName
 */
SendBirdUser.prototype['friendName'] = undefined;

/**
 * @member {Boolean} isActive
 */
SendBirdUser.prototype['isActive'] = undefined;

/**
 * @member {String} lastSeenAt
 */
SendBirdUser.prototype['lastSeenAt'] = undefined;

/**
 * @member {module:model/ModelObject} metaData
 */
SendBirdUser.prototype['metaData'] = undefined;

/**
 * @member {String} nickname
 */
SendBirdUser.prototype['nickname'] = undefined;

/**
 * @member {String} plainProfileUrl
 */
SendBirdUser.prototype['plainProfileUrl'] = undefined;

/**
 * @member {Array.<String>} preferredLanguages
 */
SendBirdUser.prototype['preferredLanguages'] = undefined;

/**
 * @member {String} profileUrl
 */
SendBirdUser.prototype['profileUrl'] = undefined;

/**
 * @member {Boolean} requireAuth
 */
SendBirdUser.prototype['requireAuth'] = undefined;

/**
 * @member {String} userId
 */
SendBirdUser.prototype['userId'] = undefined;






export default SendBirdUser;

