/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendBirdUser from './SendBirdUser';

/**
 * The SendBirdGroupChannelParams model module.
 * @module model/SendBirdGroupChannelParams
 * @version 1.0.0
 */
class SendBirdGroupChannelParams {
    /**
     * Constructs a new <code>SendBirdGroupChannelParams</code>.
     * GroupChannel
     * @alias module:model/SendBirdGroupChannelParams
     */
    constructor() { 
        
        SendBirdGroupChannelParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdGroupChannelParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdGroupChannelParams} obj Optional instance to populate.
     * @return {module:model/SendBirdGroupChannelParams} The populated <code>SendBirdGroupChannelParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdGroupChannelParams();

            if (data.hasOwnProperty('accessCode')) {
                obj['accessCode'] = ApiClient.convertToType(data['accessCode'], 'String');
            }
            if (data.hasOwnProperty('channelUrl')) {
                obj['channelUrl'] = ApiClient.convertToType(data['channelUrl'], 'String');
            }
            if (data.hasOwnProperty('coverImage')) {
                obj['coverImage'] = File.constructFromObject(data['coverImage']);
            }
            if (data.hasOwnProperty('coverUrl')) {
                obj['coverUrl'] = ApiClient.convertToType(data['coverUrl'], 'String');
            }
            if (data.hasOwnProperty('customType')) {
                obj['customType'] = ApiClient.convertToType(data['customType'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('isBroadcast')) {
                obj['isBroadcast'] = ApiClient.convertToType(data['isBroadcast'], 'Boolean');
            }
            if (data.hasOwnProperty('isDiscoverable')) {
                obj['isDiscoverable'] = ApiClient.convertToType(data['isDiscoverable'], 'Boolean');
            }
            if (data.hasOwnProperty('isDistinct')) {
                obj['isDistinct'] = ApiClient.convertToType(data['isDistinct'], 'Boolean');
            }
            if (data.hasOwnProperty('isEphemeral')) {
                obj['isEphemeral'] = ApiClient.convertToType(data['isEphemeral'], 'Boolean');
            }
            if (data.hasOwnProperty('isPublic')) {
                obj['isPublic'] = ApiClient.convertToType(data['isPublic'], 'Boolean');
            }
            if (data.hasOwnProperty('isStrict')) {
                obj['isStrict'] = ApiClient.convertToType(data['isStrict'], 'Boolean');
            }
            if (data.hasOwnProperty('isSuper')) {
                obj['isSuper'] = ApiClient.convertToType(data['isSuper'], 'Boolean');
            }
            if (data.hasOwnProperty('messageSurvivalSeconds')) {
                obj['messageSurvivalSeconds'] = ApiClient.convertToType(data['messageSurvivalSeconds'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('operatorUserIds')) {
                obj['operatorUserIds'] = ApiClient.convertToType(data['operatorUserIds'], ['String']);
            }
            if (data.hasOwnProperty('operators')) {
                obj['operators'] = ApiClient.convertToType(data['operators'], [SendBirdUser]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} accessCode
 */
SendBirdGroupChannelParams.prototype['accessCode'] = undefined;

/**
 * @member {String} channelUrl
 */
SendBirdGroupChannelParams.prototype['channelUrl'] = undefined;

/**
 * @member {File} coverImage
 */
SendBirdGroupChannelParams.prototype['coverImage'] = undefined;

/**
 * @member {String} coverUrl
 */
SendBirdGroupChannelParams.prototype['coverUrl'] = undefined;

/**
 * @member {String} customType
 */
SendBirdGroupChannelParams.prototype['customType'] = undefined;

/**
 * @member {String} data
 */
SendBirdGroupChannelParams.prototype['data'] = undefined;

/**
 * @member {Boolean} isBroadcast
 */
SendBirdGroupChannelParams.prototype['isBroadcast'] = undefined;

/**
 * @member {Boolean} isDiscoverable
 */
SendBirdGroupChannelParams.prototype['isDiscoverable'] = undefined;

/**
 * @member {Boolean} isDistinct
 */
SendBirdGroupChannelParams.prototype['isDistinct'] = undefined;

/**
 * @member {Boolean} isEphemeral
 */
SendBirdGroupChannelParams.prototype['isEphemeral'] = undefined;

/**
 * @member {Boolean} isPublic
 */
SendBirdGroupChannelParams.prototype['isPublic'] = undefined;

/**
 * @member {Boolean} isStrict
 */
SendBirdGroupChannelParams.prototype['isStrict'] = undefined;

/**
 * @member {Boolean} isSuper
 */
SendBirdGroupChannelParams.prototype['isSuper'] = undefined;

/**
 * @member {Number} messageSurvivalSeconds
 */
SendBirdGroupChannelParams.prototype['messageSurvivalSeconds'] = undefined;

/**
 * @member {String} name
 */
SendBirdGroupChannelParams.prototype['name'] = undefined;

/**
 * @member {Array.<String>} operatorUserIds
 */
SendBirdGroupChannelParams.prototype['operatorUserIds'] = undefined;

/**
 * @member {Array.<module:model/SendBirdUser>} operators
 */
SendBirdGroupChannelParams.prototype['operators'] = undefined;






export default SendBirdGroupChannelParams;

