/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendbirdBasicUserInfo from './SendbirdBasicUserInfo';
import SendbirdExtendedMessagePayload from './SendbirdExtendedMessagePayload';
import SendbirdFile from './SendbirdFile';
import SendbirdMessageResponseMessageEvents from './SendbirdMessageResponseMessageEvents';
import SendbirdParentMessageInfo from './SendbirdParentMessageInfo';
import SendbirdReaction from './SendbirdReaction';
import SendbirdSortedMetaarrayInner from './SendbirdSortedMetaarrayInner';

/**
 * The SendbirdMessageResponse model module.
 * @module model/SendbirdMessageResponse
 * @version 2.1.2
 */
class SendbirdMessageResponse {
    /**
     * Constructs a new <code>SendbirdMessageResponse</code>.
     * @alias module:model/SendbirdMessageResponse
     */
    constructor() { 
        
        SendbirdMessageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendbirdMessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendbirdMessageResponse} obj Optional instance to populate.
     * @return {module:model/SendbirdMessageResponse} The populated <code>SendbirdMessageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendbirdMessageResponse();

            if (data.hasOwnProperty('require_auth')) {
                obj['require_auth'] = ApiClient.convertToType(data['require_auth'], 'Boolean');
            }
            if (data.hasOwnProperty('message_survival_seconds')) {
                obj['message_survival_seconds'] = ApiClient.convertToType(data['message_survival_seconds'], 'Number');
            }
            if (data.hasOwnProperty('custom_type')) {
                obj['custom_type'] = ApiClient.convertToType(data['custom_type'], 'String');
            }
            if (data.hasOwnProperty('mentioned_users')) {
                obj['mentioned_users'] = ApiClient.convertToType(data['mentioned_users'], [SendbirdBasicUserInfo]);
            }
            if (data.hasOwnProperty('translations')) {
                obj['translations'] = ApiClient.convertToType(data['translations'], Object);
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Number');
            }
            if (data.hasOwnProperty('is_op_msg')) {
                obj['is_op_msg'] = ApiClient.convertToType(data['is_op_msg'], 'Boolean');
            }
            if (data.hasOwnProperty('reactions')) {
                obj['reactions'] = ApiClient.convertToType(data['reactions'], [SendbirdReaction]);
            }
            if (data.hasOwnProperty('is_removed')) {
                obj['is_removed'] = ApiClient.convertToType(data['is_removed'], 'Boolean');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = SendbirdBasicUserInfo.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], Object);
            }
            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], [SendbirdFile]);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('message_retention_hour')) {
                obj['message_retention_hour'] = ApiClient.convertToType(data['message_retention_hour'], 'Number');
            }
            if (data.hasOwnProperty('silent')) {
                obj['silent'] = ApiClient.convertToType(data['silent'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('channel_type')) {
                obj['channel_type'] = ApiClient.convertToType(data['channel_type'], 'String');
            }
            if (data.hasOwnProperty('req_id')) {
                obj['req_id'] = ApiClient.convertToType(data['req_id'], 'String');
            }
            if (data.hasOwnProperty('mention_type')) {
                obj['mention_type'] = ApiClient.convertToType(data['mention_type'], 'String');
            }
            if (data.hasOwnProperty('channel_url')) {
                obj['channel_url'] = ApiClient.convertToType(data['channel_url'], 'String');
            }
            if (data.hasOwnProperty('message_id')) {
                obj['message_id'] = ApiClient.convertToType(data['message_id'], 'Number');
            }
            if (data.hasOwnProperty('sorted_metaarray')) {
                obj['sorted_metaarray'] = ApiClient.convertToType(data['sorted_metaarray'], [SendbirdSortedMetaarrayInner]);
            }
            if (data.hasOwnProperty('thread_info')) {
                obj['thread_info'] = ApiClient.convertToType(data['thread_info'], Object);
            }
            if (data.hasOwnProperty('parent_message_id')) {
                obj['parent_message_id'] = ApiClient.convertToType(data['parent_message_id'], 'Number');
            }
            if (data.hasOwnProperty('parent_message_info')) {
                obj['parent_message_info'] = SendbirdParentMessageInfo.constructFromObject(data['parent_message_info']);
            }
            if (data.hasOwnProperty('is_reply_to_channel')) {
                obj['is_reply_to_channel'] = ApiClient.convertToType(data['is_reply_to_channel'], 'Boolean');
            }
            if (data.hasOwnProperty('message_events')) {
                obj['message_events'] = SendbirdMessageResponseMessageEvents.constructFromObject(data['message_events']);
            }
            if (data.hasOwnProperty('extended_message_payload')) {
                obj['extended_message_payload'] = SendbirdExtendedMessagePayload.constructFromObject(data['extended_message_payload']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} require_auth
 */
SendbirdMessageResponse.prototype['require_auth'] = undefined;

/**
 * @member {Number} message_survival_seconds
 */
SendbirdMessageResponse.prototype['message_survival_seconds'] = undefined;

/**
 * @member {String} custom_type
 */
SendbirdMessageResponse.prototype['custom_type'] = undefined;

/**
 * @member {Array.<module:model/SendbirdBasicUserInfo>} mentioned_users
 */
SendbirdMessageResponse.prototype['mentioned_users'] = undefined;

/**
 * @member {Object} translations
 */
SendbirdMessageResponse.prototype['translations'] = undefined;

/**
 * @member {Number} updated_at
 */
SendbirdMessageResponse.prototype['updated_at'] = undefined;

/**
 * @member {Boolean} is_op_msg
 */
SendbirdMessageResponse.prototype['is_op_msg'] = undefined;

/**
 * @member {Array.<module:model/SendbirdReaction>} reactions
 */
SendbirdMessageResponse.prototype['reactions'] = undefined;

/**
 * @member {Boolean} is_removed
 */
SendbirdMessageResponse.prototype['is_removed'] = undefined;

/**
 * @member {module:model/SendbirdBasicUserInfo} user
 */
SendbirdMessageResponse.prototype['user'] = undefined;

/**
 * @member {Object} file
 */
SendbirdMessageResponse.prototype['file'] = undefined;

/**
 * @member {Array.<module:model/SendbirdFile>} files
 */
SendbirdMessageResponse.prototype['files'] = undefined;

/**
 * @member {String} message
 */
SendbirdMessageResponse.prototype['message'] = undefined;

/**
 * @member {String} data
 */
SendbirdMessageResponse.prototype['data'] = undefined;

/**
 * @member {Number} message_retention_hour
 */
SendbirdMessageResponse.prototype['message_retention_hour'] = undefined;

/**
 * @member {Boolean} silent
 */
SendbirdMessageResponse.prototype['silent'] = undefined;

/**
 * @member {String} type
 */
SendbirdMessageResponse.prototype['type'] = undefined;

/**
 * @member {Number} created_at
 */
SendbirdMessageResponse.prototype['created_at'] = undefined;

/**
 * @member {String} channel_type
 */
SendbirdMessageResponse.prototype['channel_type'] = undefined;

/**
 * @member {String} req_id
 */
SendbirdMessageResponse.prototype['req_id'] = undefined;

/**
 * @member {String} mention_type
 */
SendbirdMessageResponse.prototype['mention_type'] = undefined;

/**
 * @member {String} channel_url
 */
SendbirdMessageResponse.prototype['channel_url'] = undefined;

/**
 * @member {Number} message_id
 */
SendbirdMessageResponse.prototype['message_id'] = undefined;

/**
 * @member {Array.<module:model/SendbirdSortedMetaarrayInner>} sorted_metaarray
 */
SendbirdMessageResponse.prototype['sorted_metaarray'] = undefined;

/**
 * @member {Object} thread_info
 */
SendbirdMessageResponse.prototype['thread_info'] = undefined;

/**
 * @member {Number} parent_message_id
 */
SendbirdMessageResponse.prototype['parent_message_id'] = undefined;

/**
 * @member {module:model/SendbirdParentMessageInfo} parent_message_info
 */
SendbirdMessageResponse.prototype['parent_message_info'] = undefined;

/**
 * @member {Boolean} is_reply_to_channel
 */
SendbirdMessageResponse.prototype['is_reply_to_channel'] = undefined;

/**
 * @member {module:model/SendbirdMessageResponseMessageEvents} message_events
 */
SendbirdMessageResponse.prototype['message_events'] = undefined;

/**
 * @member {module:model/SendbirdExtendedMessagePayload} extended_message_payload
 */
SendbirdMessageResponse.prototype['extended_message_payload'] = undefined;






export default SendbirdMessageResponse;

