/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendBirdPollUpdatedVoteCount model module.
 * @module model/SendBirdPollUpdatedVoteCount
 * @version 0.0.14
 */
class SendBirdPollUpdatedVoteCount {
    /**
     * Constructs a new <code>SendBirdPollUpdatedVoteCount</code>.
     * @alias module:model/SendBirdPollUpdatedVoteCount
     */
    constructor() { 
        
        SendBirdPollUpdatedVoteCount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdPollUpdatedVoteCount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdPollUpdatedVoteCount} obj Optional instance to populate.
     * @return {module:model/SendBirdPollUpdatedVoteCount} The populated <code>SendBirdPollUpdatedVoteCount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdPollUpdatedVoteCount();

            if (data.hasOwnProperty('option_id')) {
                obj['option_id'] = ApiClient.convertToType(data['option_id'], 'Number');
            }
            if (data.hasOwnProperty('vote_count')) {
                obj['vote_count'] = ApiClient.convertToType(data['vote_count'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} option_id
 */
SendBirdPollUpdatedVoteCount.prototype['option_id'] = undefined;

/**
 * @member {Number} vote_count
 */
SendBirdPollUpdatedVoteCount.prototype['vote_count'] = undefined;






export default SendBirdPollUpdatedVoteCount;

