/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendBirdAppleCriticalAlertOptions from './SendBirdAppleCriticalAlertOptions';
import SendBirdMessageMetaArray from './SendBirdMessageMetaArray';
import SendBirdUser from './SendBirdUser';

/**
 * The SendBirdBaseMessageParams model module.
 * @module model/SendBirdBaseMessageParams
 * @version 1.0.0
 */
class SendBirdBaseMessageParams {
    /**
     * Constructs a new <code>SendBirdBaseMessageParams</code>.
     * @alias module:model/SendBirdBaseMessageParams
     */
    constructor() { 
        
        SendBirdBaseMessageParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdBaseMessageParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdBaseMessageParams} obj Optional instance to populate.
     * @return {module:model/SendBirdBaseMessageParams} The populated <code>SendBirdBaseMessageParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdBaseMessageParams();

            if (data.hasOwnProperty('appleCriticalAlertOptions')) {
                obj['appleCriticalAlertOptions'] = SendBirdAppleCriticalAlertOptions.constructFromObject(data['appleCriticalAlertOptions']);
            }
            if (data.hasOwnProperty('customType')) {
                obj['customType'] = ApiClient.convertToType(data['customType'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('isReplyToChannel')) {
                obj['isReplyToChannel'] = ApiClient.convertToType(data['isReplyToChannel'], 'Boolean');
            }
            if (data.hasOwnProperty('mentionType')) {
                obj['mentionType'] = ApiClient.convertToType(data['mentionType'], 'String');
            }
            if (data.hasOwnProperty('mentionedUserIds')) {
                obj['mentionedUserIds'] = ApiClient.convertToType(data['mentionedUserIds'], ['String']);
            }
            if (data.hasOwnProperty('mentionedUsers')) {
                obj['mentionedUsers'] = ApiClient.convertToType(data['mentionedUsers'], [SendBirdUser]);
            }
            if (data.hasOwnProperty('metaArrayKeys')) {
                obj['metaArrayKeys'] = ApiClient.convertToType(data['metaArrayKeys'], ['String']);
            }
            if (data.hasOwnProperty('metaArrays')) {
                obj['metaArrays'] = ApiClient.convertToType(data['metaArrays'], [SendBirdMessageMetaArray]);
            }
            if (data.hasOwnProperty('parentMessageId')) {
                obj['parentMessageId'] = ApiClient.convertToType(data['parentMessageId'], 'Number');
            }
            if (data.hasOwnProperty('pushNotificationDeliveryOption')) {
                obj['pushNotificationDeliveryOption'] = ApiClient.convertToType(data['pushNotificationDeliveryOption'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdAppleCriticalAlertOptions} appleCriticalAlertOptions
 */
SendBirdBaseMessageParams.prototype['appleCriticalAlertOptions'] = undefined;

/**
 * @member {String} customType
 */
SendBirdBaseMessageParams.prototype['customType'] = undefined;

/**
 * @member {String} data
 */
SendBirdBaseMessageParams.prototype['data'] = undefined;

/**
 * @member {Boolean} isReplyToChannel
 */
SendBirdBaseMessageParams.prototype['isReplyToChannel'] = undefined;

/**
 * @member {module:model/SendBirdBaseMessageParams.MentionTypeEnum} mentionType
 */
SendBirdBaseMessageParams.prototype['mentionType'] = undefined;

/**
 * @member {Array.<String>} mentionedUserIds
 */
SendBirdBaseMessageParams.prototype['mentionedUserIds'] = undefined;

/**
 * @member {Array.<module:model/SendBirdUser>} mentionedUsers
 */
SendBirdBaseMessageParams.prototype['mentionedUsers'] = undefined;

/**
 * @member {Array.<String>} metaArrayKeys
 */
SendBirdBaseMessageParams.prototype['metaArrayKeys'] = undefined;

/**
 * @member {Array.<module:model/SendBirdMessageMetaArray>} metaArrays
 */
SendBirdBaseMessageParams.prototype['metaArrays'] = undefined;

/**
 * @member {Number} parentMessageId
 */
SendBirdBaseMessageParams.prototype['parentMessageId'] = undefined;

/**
 * @member {module:model/SendBirdBaseMessageParams.PushNotificationDeliveryOptionEnum} pushNotificationDeliveryOption
 */
SendBirdBaseMessageParams.prototype['pushNotificationDeliveryOption'] = undefined;





/**
 * Allowed values for the <code>mentionType</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdBaseMessageParams['MentionTypeEnum'] = {

    /**
     * value: "channel"
     * @const
     */
    "channel": "channel",

    /**
     * value: "users"
     * @const
     */
    "users": "users"
};


/**
 * Allowed values for the <code>pushNotificationDeliveryOption</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdBaseMessageParams['PushNotificationDeliveryOptionEnum'] = {

    /**
     * value: "default"
     * @const
     */
    "default": "default",

    /**
     * value: "suppress"
     * @const
     */
    "suppress": "suppress"
};



export default SendBirdBaseMessageParams;

