/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendBirdGroupChannelCollectionStaticGroupChannelOrder from './SendBirdGroupChannelCollectionStaticGroupChannelOrder';

/**
 * The SendBirdGroupChannelCollectionStatic model module.
 * @module model/SendBirdGroupChannelCollectionStatic
 * @version 1.0.0
 */
class SendBirdGroupChannelCollectionStatic {
    /**
     * Constructs a new <code>SendBirdGroupChannelCollectionStatic</code>.
     * @alias module:model/SendBirdGroupChannelCollectionStatic
     */
    constructor() { 
        
        SendBirdGroupChannelCollectionStatic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdGroupChannelCollectionStatic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdGroupChannelCollectionStatic} obj Optional instance to populate.
     * @return {module:model/SendBirdGroupChannelCollectionStatic} The populated <code>SendBirdGroupChannelCollectionStatic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdGroupChannelCollectionStatic();

            if (data.hasOwnProperty('GroupChannelOrder')) {
                obj['GroupChannelOrder'] = SendBirdGroupChannelCollectionStaticGroupChannelOrder.constructFromObject(data['GroupChannelOrder']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdGroupChannelCollectionStaticGroupChannelOrder} GroupChannelOrder
 */
SendBirdGroupChannelCollectionStatic.prototype['GroupChannelOrder'] = undefined;






export default SendBirdGroupChannelCollectionStatic;

