/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendBirdMessageTypeFilter model module.
 * @module model/SendBirdMessageTypeFilter
 * @version 1.0.0
 */
class SendBirdMessageTypeFilter {
    /**
     * Constructs a new <code>SendBirdMessageTypeFilter</code>.
     * @alias module:model/SendBirdMessageTypeFilter
     */
    constructor() { 
        
        SendBirdMessageTypeFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdMessageTypeFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdMessageTypeFilter} obj Optional instance to populate.
     * @return {module:model/SendBirdMessageTypeFilter} The populated <code>SendBirdMessageTypeFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdMessageTypeFilter();

            if (data.hasOwnProperty('ADMIN')) {
                obj['ADMIN'] = ApiClient.convertToType(data['ADMIN'], 'String');
            }
            if (data.hasOwnProperty('ALL')) {
                obj['ALL'] = ApiClient.convertToType(data['ALL'], 'String');
            }
            if (data.hasOwnProperty('FILE')) {
                obj['FILE'] = ApiClient.convertToType(data['FILE'], 'String');
            }
            if (data.hasOwnProperty('USER')) {
                obj['USER'] = ApiClient.convertToType(data['USER'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdMessageTypeFilter.ADMINEnum} ADMIN
 */
SendBirdMessageTypeFilter.prototype['ADMIN'] = undefined;

/**
 * @member {module:model/SendBirdMessageTypeFilter.ALLEnum} ALL
 */
SendBirdMessageTypeFilter.prototype['ALL'] = undefined;

/**
 * @member {module:model/SendBirdMessageTypeFilter.FILEEnum} FILE
 */
SendBirdMessageTypeFilter.prototype['FILE'] = undefined;

/**
 * @member {module:model/SendBirdMessageTypeFilter.USEREnum} USER
 */
SendBirdMessageTypeFilter.prototype['USER'] = undefined;





/**
 * Allowed values for the <code>ADMIN</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdMessageTypeFilter['ADMINEnum'] = {

    /**
     * value: "ADMM"
     * @const
     */
    "ADMM": "ADMM"
};


/**
 * Allowed values for the <code>ALL</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdMessageTypeFilter['ALLEnum'] = {

    /**
     * value: ""
     * @const
     */
    "empty": ""
};


/**
 * Allowed values for the <code>FILE</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdMessageTypeFilter['FILEEnum'] = {

    /**
     * value: "FILE"
     * @const
     */
    "FILE": "FILE"
};


/**
 * Allowed values for the <code>USER</code> property.
 * @enum {String}
 * @readonly
 */
SendBirdMessageTypeFilter['USEREnum'] = {

    /**
     * value: "MESG"
     * @const
     */
    "MESG": "MESG"
};



export default SendBirdMessageTypeFilter;

