/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendBirdEmoji from './SendBirdEmoji';

/**
 * The SendBirdEmojiCategory model module.
 * @module model/SendBirdEmojiCategory
 * @version 1.0.3
 */
class SendBirdEmojiCategory {
    /**
     * Constructs a new <code>SendBirdEmojiCategory</code>.
     * @alias module:model/SendBirdEmojiCategory
     */
    constructor() { 
        
        SendBirdEmojiCategory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdEmojiCategory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdEmojiCategory} obj Optional instance to populate.
     * @return {module:model/SendBirdEmojiCategory} The populated <code>SendBirdEmojiCategory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdEmojiCategory();

            if (data.hasOwnProperty('emojis')) {
                obj['emojis'] = ApiClient.convertToType(data['emojis'], [SendBirdEmoji]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/SendBirdEmoji>} emojis
 */
SendBirdEmojiCategory.prototype['emojis'] = undefined;

/**
 * @member {Number} id
 */
SendBirdEmojiCategory.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SendBirdEmojiCategory.prototype['name'] = undefined;

/**
 * @member {String} url
 */
SendBirdEmojiCategory.prototype['url'] = undefined;






export default SendBirdEmojiCategory;

