/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SendBirdGroupChannelFilterStaticHiddenChannelFilter from './SendBirdGroupChannelFilterStaticHiddenChannelFilter';
import SendBirdGroupChannelFilterStaticMemberStateFilter from './SendBirdGroupChannelFilterStaticMemberStateFilter';
import SendBirdGroupChannelFilterStaticPublicChannelFilter from './SendBirdGroupChannelFilterStaticPublicChannelFilter';
import SendBirdGroupChannelFilterStaticQueryType from './SendBirdGroupChannelFilterStaticQueryType';
import SendBirdGroupChannelFilterStaticSearchField from './SendBirdGroupChannelFilterStaticSearchField';
import SendBirdGroupChannelFilterStaticSuperChannelFilter from './SendBirdGroupChannelFilterStaticSuperChannelFilter';
import SendBirdGroupChannelFilterStaticUnreadChannelFilter from './SendBirdGroupChannelFilterStaticUnreadChannelFilter';

/**
 * The SendBirdGroupChannelFilterStatic model module.
 * @module model/SendBirdGroupChannelFilterStatic
 * @version 1.0.0
 */
class SendBirdGroupChannelFilterStatic {
    /**
     * Constructs a new <code>SendBirdGroupChannelFilterStatic</code>.
     * @alias module:model/SendBirdGroupChannelFilterStatic
     */
    constructor() { 
        
        SendBirdGroupChannelFilterStatic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendBirdGroupChannelFilterStatic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendBirdGroupChannelFilterStatic} obj Optional instance to populate.
     * @return {module:model/SendBirdGroupChannelFilterStatic} The populated <code>SendBirdGroupChannelFilterStatic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendBirdGroupChannelFilterStatic();

            if (data.hasOwnProperty('HiddenChannelFilter')) {
                obj['HiddenChannelFilter'] = SendBirdGroupChannelFilterStaticHiddenChannelFilter.constructFromObject(data['HiddenChannelFilter']);
            }
            if (data.hasOwnProperty('MemberStateFilter')) {
                obj['MemberStateFilter'] = SendBirdGroupChannelFilterStaticMemberStateFilter.constructFromObject(data['MemberStateFilter']);
            }
            if (data.hasOwnProperty('PublicChannelFilter')) {
                obj['PublicChannelFilter'] = SendBirdGroupChannelFilterStaticPublicChannelFilter.constructFromObject(data['PublicChannelFilter']);
            }
            if (data.hasOwnProperty('QueryType')) {
                obj['QueryType'] = SendBirdGroupChannelFilterStaticQueryType.constructFromObject(data['QueryType']);
            }
            if (data.hasOwnProperty('SearchField')) {
                obj['SearchField'] = SendBirdGroupChannelFilterStaticSearchField.constructFromObject(data['SearchField']);
            }
            if (data.hasOwnProperty('SuperChannelFilter')) {
                obj['SuperChannelFilter'] = SendBirdGroupChannelFilterStaticSuperChannelFilter.constructFromObject(data['SuperChannelFilter']);
            }
            if (data.hasOwnProperty('UnreadChannelFilter')) {
                obj['UnreadChannelFilter'] = SendBirdGroupChannelFilterStaticUnreadChannelFilter.constructFromObject(data['UnreadChannelFilter']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticHiddenChannelFilter} HiddenChannelFilter
 */
SendBirdGroupChannelFilterStatic.prototype['HiddenChannelFilter'] = undefined;

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticMemberStateFilter} MemberStateFilter
 */
SendBirdGroupChannelFilterStatic.prototype['MemberStateFilter'] = undefined;

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticPublicChannelFilter} PublicChannelFilter
 */
SendBirdGroupChannelFilterStatic.prototype['PublicChannelFilter'] = undefined;

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticQueryType} QueryType
 */
SendBirdGroupChannelFilterStatic.prototype['QueryType'] = undefined;

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticSearchField} SearchField
 */
SendBirdGroupChannelFilterStatic.prototype['SearchField'] = undefined;

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticSuperChannelFilter} SuperChannelFilter
 */
SendBirdGroupChannelFilterStatic.prototype['SuperChannelFilter'] = undefined;

/**
 * @member {module:model/SendBirdGroupChannelFilterStaticUnreadChannelFilter} UnreadChannelFilter
 */
SendBirdGroupChannelFilterStatic.prototype['UnreadChannelFilter'] = undefined;






export default SendBirdGroupChannelFilterStatic;

