/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetDomainFilterDataDomainFilter model module.
 * @module model/SetDomainFilterDataDomainFilter
 * @version 0.0.14
 */
class SetDomainFilterDataDomainFilter {
    /**
     * Constructs a new <code>SetDomainFilterDataDomainFilter</code>.
     * @alias module:model/SetDomainFilterDataDomainFilter
     */
    constructor() { 
        
        SetDomainFilterDataDomainFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetDomainFilterDataDomainFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetDomainFilterDataDomainFilter} obj Optional instance to populate.
     * @return {module:model/SetDomainFilterDataDomainFilter} The populated <code>SetDomainFilterDataDomainFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetDomainFilterDataDomainFilter();

            if (data.hasOwnProperty('domains')) {
                obj['domains'] = ApiClient.convertToType(data['domains'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('should_check_global')) {
                obj['should_check_global'] = ApiClient.convertToType(data['should_check_global'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} domains
 */
SetDomainFilterDataDomainFilter.prototype['domains'] = undefined;

/**
 * @member {Number} type
 */
SetDomainFilterDataDomainFilter.prototype['type'] = undefined;

/**
 * @member {Boolean} should_check_global
 */
SetDomainFilterDataDomainFilter.prototype['should_check_global'] = undefined;






export default SetDomainFilterDataDomainFilter;

