/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateAnOpenChannelRequest model module.
 * @module model/UpdateAnOpenChannelRequest
 * @version 2.0.0
 */
class UpdateAnOpenChannelRequest {
    /**
     * Constructs a new <code>UpdateAnOpenChannelRequest</code>.
     * @alias module:model/UpdateAnOpenChannelRequest
     */
    constructor() { 
        
        UpdateAnOpenChannelRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateAnOpenChannelRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateAnOpenChannelRequest} obj Optional instance to populate.
     * @return {module:model/UpdateAnOpenChannelRequest} The populated <code>UpdateAnOpenChannelRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateAnOpenChannelRequest();

            if (data.hasOwnProperty('cover_file')) {
                obj['cover_file'] = ApiClient.convertToType(data['cover_file'], File);
            }
            if (data.hasOwnProperty('cover_url')) {
                obj['cover_url'] = ApiClient.convertToType(data['cover_url'], 'String');
            }
            if (data.hasOwnProperty('custom_type')) {
                obj['custom_type'] = ApiClient.convertToType(data['custom_type'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('operator_ids')) {
                obj['operator_ids'] = ApiClient.convertToType(data['operator_ids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {File} cover_file
 */
UpdateAnOpenChannelRequest.prototype['cover_file'] = undefined;

/**
 * @member {String} cover_url
 */
UpdateAnOpenChannelRequest.prototype['cover_url'] = undefined;

/**
 * @member {String} custom_type
 */
UpdateAnOpenChannelRequest.prototype['custom_type'] = undefined;

/**
 * @member {String} data
 */
UpdateAnOpenChannelRequest.prototype['data'] = undefined;

/**
 * @member {String} name
 */
UpdateAnOpenChannelRequest.prototype['name'] = undefined;

/**
 * @member {Array.<String>} operator_ids
 */
UpdateAnOpenChannelRequest.prototype['operator_ids'] = undefined;






export default UpdateAnOpenChannelRequest;

