/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateFcmPushConfigurationByIdResponse model module.
 * @module model/UpdateFcmPushConfigurationByIdResponse
 * @version 0.0.14
 */
class UpdateFcmPushConfigurationByIdResponse {
    /**
     * Constructs a new <code>UpdateFcmPushConfigurationByIdResponse</code>.
     * @alias module:model/UpdateFcmPushConfigurationByIdResponse
     */
    constructor() { 
        
        UpdateFcmPushConfigurationByIdResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateFcmPushConfigurationByIdResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateFcmPushConfigurationByIdResponse} obj Optional instance to populate.
     * @return {module:model/UpdateFcmPushConfigurationByIdResponse} The populated <code>UpdateFcmPushConfigurationByIdResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateFcmPushConfigurationByIdResponse();

            if (data.hasOwnProperty('push_configurations')) {
                obj['push_configurations'] = ApiClient.convertToType(data['push_configurations'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} push_configurations
 */
UpdateFcmPushConfigurationByIdResponse.prototype['push_configurations'] = undefined;






export default UpdateFcmPushConfigurationByIdResponse;

