/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateUserMetadataRequest model module.
 * @module model/UpdateUserMetadataRequest
 * @version 2.1.2
 */
class UpdateUserMetadataRequest {
    /**
     * Constructs a new <code>UpdateUserMetadataRequest</code>.
     * @alias module:model/UpdateUserMetadataRequest
     * @param metadata {Object} 
     */
    constructor(metadata) { 
        
        UpdateUserMetadataRequest.initialize(this, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metadata) { 
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>UpdateUserMetadataRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUserMetadataRequest} obj Optional instance to populate.
     * @return {module:model/UpdateUserMetadataRequest} The populated <code>UpdateUserMetadataRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUserMetadataRequest();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('upsert')) {
                obj['upsert'] = ApiClient.convertToType(data['upsert'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} metadata
 */
UpdateUserMetadataRequest.prototype['metadata'] = undefined;

/**
 * @member {Boolean} upsert
 */
UpdateUserMetadataRequest.prototype['upsert'] = undefined;






export default UpdateUserMetadataRequest;

