/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateDefaultChannelInvitationPreferenceData model module.
 * @module model/UpdateDefaultChannelInvitationPreferenceData
 * @version 1.0.0
 */
class UpdateDefaultChannelInvitationPreferenceData {
    /**
     * Constructs a new <code>UpdateDefaultChannelInvitationPreferenceData</code>.
     * @alias module:model/UpdateDefaultChannelInvitationPreferenceData
     * @param autoAccept {Boolean} Determines for users within an application whether or not to automatically join a [private](/docs/chat/v3/platform-api/guides/group-channel#-3-private-vs-public) group channel promptly from an invitation without having to accept it. (Default: true)
     */
    constructor(autoAccept) { 
        
        UpdateDefaultChannelInvitationPreferenceData.initialize(this, autoAccept);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, autoAccept) { 
        obj['auto_accept'] = autoAccept;
    }

    /**
     * Constructs a <code>UpdateDefaultChannelInvitationPreferenceData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDefaultChannelInvitationPreferenceData} obj Optional instance to populate.
     * @return {module:model/UpdateDefaultChannelInvitationPreferenceData} The populated <code>UpdateDefaultChannelInvitationPreferenceData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDefaultChannelInvitationPreferenceData();

            if (data.hasOwnProperty('auto_accept')) {
                obj['auto_accept'] = ApiClient.convertToType(data['auto_accept'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Determines for users within an application whether or not to automatically join a [private](/docs/chat/v3/platform-api/guides/group-channel#-3-private-vs-public) group channel promptly from an invitation without having to accept it. (Default: true)
 * @member {Boolean} auto_accept
 */
UpdateDefaultChannelInvitationPreferenceData.prototype['auto_accept'] = undefined;






export default UpdateDefaultChannelInvitationPreferenceData;

