/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration model module.
 * @module model/V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration
 * @version 1.0.3
 */
class V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration {
    /**
     * Constructs a new <code>V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration</code>.
     * @alias module:model/V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration
     */
    constructor() { 
        
        V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration} obj Optional instance to populate.
     * @return {module:model/V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration} The populated <code>V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} count
 */
V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration.prototype['count'] = undefined;

/**
 * @member {Number} duration
 */
V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration.prototype['duration'] = undefined;

/**
 * @member {Number} action
 */
V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration.prototype['action'] = undefined;






export default V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration;

