/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ScheduleAnAnnouncementRequest from '../model/ScheduleAnAnnouncementRequest';
import ScheduleAnAnnouncementResponse from '../model/ScheduleAnAnnouncementResponse';

/**
* Announcement service.
* @module api/AnnouncementApi
* @version 2.1.1
*/
export default class AnnouncementApi {

    /**
    * Constructs a new AnnouncementApi. 
    * @alias module:api/AnnouncementApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Schedule an announcement
     * ## Schedule an announcement  Creates an announcement. You can also schedule an announcement in the [Sendbird Dashboard](https://dashboard.sendbird.com).  [https://sendbird.com/docs/chat/platform-api/v3/message/announcements/create-an-announcement#1-create-an-announcement](https://sendbird.com/docs/chat/platform-api/v3/message/announcements/create-an-announcement#1-create-an-announcement)
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiToken 
     * @param {module:model/ScheduleAnAnnouncementRequest} opts.scheduleAnAnnouncementRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ScheduleAnAnnouncementResponse} and HTTP response
     */
    scheduleAnAnnouncementWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['scheduleAnAnnouncementRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'api-token': opts['apiToken']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ScheduleAnAnnouncementResponse;
      return this.apiClient.callApi(
        '/v3/announcements', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Schedule an announcement
     * ## Schedule an announcement  Creates an announcement. You can also schedule an announcement in the [Sendbird Dashboard](https://dashboard.sendbird.com).  [https://sendbird.com/docs/chat/platform-api/v3/message/announcements/create-an-announcement#1-create-an-announcement](https://sendbird.com/docs/chat/platform-api/v3/message/announcements/create-an-announcement#1-create-an-announcement)
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiToken 
     * @param {module:model/ScheduleAnAnnouncementRequest} opts.scheduleAnAnnouncementRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ScheduleAnAnnouncementResponse}
     */
    scheduleAnAnnouncement(opts) {
      return this.scheduleAnAnnouncementWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
