/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendbirdPlatformSdk);
  }
}(this, function(expect, SendbirdPlatformSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SendBirdStaticLogLevel', function() {
    it('should create an instance of SendBirdStaticLogLevel', function() {
      // uncomment below and update the code to test SendBirdStaticLogLevel
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be.a(SendbirdPlatformSdk.SendBirdStaticLogLevel);
    });

    it('should have the property DEBUG (base name: "DEBUG")', function() {
      // uncomment below and update the code to test the property DEBUG
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be();
    });

    it('should have the property ERROR (base name: "ERROR")', function() {
      // uncomment below and update the code to test the property ERROR
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be();
    });

    it('should have the property INFO (base name: "INFO")', function() {
      // uncomment below and update the code to test the property INFO
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be();
    });

    it('should have the property NONE (base name: "NONE")', function() {
      // uncomment below and update the code to test the property NONE
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be();
    });

    it('should have the property VERBOSE (base name: "VERBOSE")', function() {
      // uncomment below and update the code to test the property VERBOSE
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be();
    });

    it('should have the property WARN (base name: "WARN")', function() {
      // uncomment below and update the code to test the property WARN
      //var instance = new SendbirdPlatformSdk.SendBirdStaticLogLevel();
      //expect(instance).to.be();
    });

  });

}));
