/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendbirdPlatformSdk);
  }
}(this, function(expect, SendbirdPlatformSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SendBirdMessageChangeLogsParams', function() {
    it('should create an instance of SendBirdMessageChangeLogsParams', function() {
      // uncomment below and update the code to test SendBirdMessageChangeLogsParams
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be.a(SendbirdPlatformSdk.SendBirdMessageChangeLogsParams);
    });

    it('should have the property includeMetaArray (base name: "includeMetaArray")', function() {
      // uncomment below and update the code to test the property includeMetaArray
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includeParentMessageInfo (base name: "includeParentMessageInfo")', function() {
      // uncomment below and update the code to test the property includeParentMessageInfo
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includeParentMessageText (base name: "includeParentMessageText")', function() {
      // uncomment below and update the code to test the property includeParentMessageText
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includePollDetails (base name: "includePollDetails")', function() {
      // uncomment below and update the code to test the property includePollDetails
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includeReaction (base name: "includeReaction")', function() {
      // uncomment below and update the code to test the property includeReaction
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includeReactions (base name: "includeReactions")', function() {
      // uncomment below and update the code to test the property includeReactions
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includeReplies (base name: "includeReplies")', function() {
      // uncomment below and update the code to test the property includeReplies
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property includeThreadInfo (base name: "includeThreadInfo")', function() {
      // uncomment below and update the code to test the property includeThreadInfo
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

    it('should have the property replyType (base name: "replyType")', function() {
      // uncomment below and update the code to test the property replyType
      //var instance = new SendbirdPlatformSdk.SendBirdMessageChangeLogsParams();
      //expect(instance).to.be();
    });

  });

}));
