/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendbirdPlatformSdk);
  }
}(this, function(expect, SendbirdPlatformSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateAnnouncementByIdResponseMessage', function() {
    it('should create an instance of UpdateAnnouncementByIdResponseMessage', function() {
      // uncomment below and update the code to test UpdateAnnouncementByIdResponseMessage
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be.a(SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property customType (base name: "custom_type")', function() {
      // uncomment below and update the code to test the property customType
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property enablePush (base name: "enable_push")', function() {
      // uncomment below and update the code to test the property enablePush
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property targetAt (base name: "target_at")', function() {
      // uncomment below and update the code to test the property targetAt
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property targetUserCount (base name: "target_user_count")', function() {
      // uncomment below and update the code to test the property targetUserCount
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property targetChannelCount (base name: "target_channel_count")', function() {
      // uncomment below and update the code to test the property targetChannelCount
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property scheduledAt (base name: "scheduled_at")', function() {
      // uncomment below and update the code to test the property scheduledAt
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property completedAt (base name: "completed_at")', function() {
      // uncomment below and update the code to test the property completedAt
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property sentUserCount (base name: "sent_user_count")', function() {
      // uncomment below and update the code to test the property sentUserCount
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property openCount (base name: "open_count")', function() {
      // uncomment below and update the code to test the property openCount
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

    it('should have the property openRate (base name: "open_rate")', function() {
      // uncomment below and update the code to test the property openRate
      //var instance = new SendbirdPlatformSdk.UpdateAnnouncementByIdResponseMessage();
      //expect(instance).to.be();
    });

  });

}));
