/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AcceptAnInvitationRequest from './model/AcceptAnInvitationRequest';
import AddARegistrationOrDeviceTokenRequest from './model/AddARegistrationOrDeviceTokenRequest';
import AddARegistrationOrDeviceTokenResponse from './model/AddARegistrationOrDeviceTokenResponse';
import AddExtraDataToAMessageRequest from './model/AddExtraDataToAMessageRequest';
import AddExtraDataToAMessageResponse from './model/AddExtraDataToAMessageResponse';
import BlockAUserRequest from './model/BlockAUserRequest';
import BlockAUserResponse from './model/BlockAUserResponse';
import CheckIfMemberResponse from './model/CheckIfMemberResponse';
import ChooseAPushNotificationContentTemplateRequest from './model/ChooseAPushNotificationContentTemplateRequest';
import ChooseAPushNotificationContentTemplateResponse from './model/ChooseAPushNotificationContentTemplateResponse';
import CreateABotRequest from './model/CreateABotRequest';
import CreateABotResponse from './model/CreateABotResponse';
import CreateABotResponseBot from './model/CreateABotResponseBot';
import CreateABotResponseBotStyle from './model/CreateABotResponseBotStyle';
import CreateAChannelMetadataRequest from './model/CreateAChannelMetadataRequest';
import CreateAChannelMetadataResponse from './model/CreateAChannelMetadataResponse';
import CreateAGroupChannelRequest from './model/CreateAGroupChannelRequest';
import CreateAUserRequest from './model/CreateAUserRequest';
import CreateAnOpenChannelRequest from './model/CreateAnOpenChannelRequest';
import CreateUserMetadataRequest from './model/CreateUserMetadataRequest';
import CreateUserTokenRequest from './model/CreateUserTokenRequest';
import CreateUserTokenResponse from './model/CreateUserTokenResponse';
import FreezeAGroupChannelRequest from './model/FreezeAGroupChannelRequest';
import FreezeAnOpenChannelRequest from './model/FreezeAnOpenChannelRequest';
import GetAGroupChannelResponse from './model/GetAGroupChannelResponse';
import GetAGroupChannelResponseAllOf from './model/GetAGroupChannelResponseAllOf';
import GetChannelInvitationPreferenceResponse from './model/GetChannelInvitationPreferenceResponse';
import GetTotalNumberOfMessagesInAChannelResponse from './model/GetTotalNumberOfMessagesInAChannelResponse';
import GroupChannelListMembersResponse from './model/GroupChannelListMembersResponse';
import GroupChatListChannelsResponse from './model/GroupChatListChannelsResponse';
import HideAChannelRequest from './model/HideAChannelRequest';
import InviteAsMembersRequest from './model/InviteAsMembersRequest';
import InviteAsMembersResponse from './model/InviteAsMembersResponse';
import InviteAsMembersResponseAllOf from './model/InviteAsMembersResponseAllOf';
import JoinAChannelRequest from './model/JoinAChannelRequest';
import JoinChannelsRequest from './model/JoinChannelsRequest';
import LeaveAChannelRequest from './model/LeaveAChannelRequest';
import LeaveMyGroupChannelsRequest from './model/LeaveMyGroupChannelsRequest';
import ListBlockedUsersResponse from './model/ListBlockedUsersResponse';
import ListBotsResponse from './model/ListBotsResponse';
import ListBotsResponseBotsInner from './model/ListBotsResponseBotsInner';
import ListBotsResponseBotsInnerAi from './model/ListBotsResponseBotsInnerAi';
import ListBotsResponseBotsInnerBot from './model/ListBotsResponseBotsInnerBot';
import ListBotsResponseBotsInnerBotStyle from './model/ListBotsResponseBotsInnerBotStyle';
import ListBotsResponseBotsInnerBotStyleColor from './model/ListBotsResponseBotsInnerBotStyleColor';
import ListBotsResponseBotsInnerFirstMessagesInner from './model/ListBotsResponseBotsInnerFirstMessagesInner';
import ListBotsResponseBotsInnerFirstMessagesInnerData from './model/ListBotsResponseBotsInnerFirstMessagesInnerData';
import ListBotsResponseBotsInnerSafeguard from './model/ListBotsResponseBotsInnerSafeguard';
import ListMessagesResponse from './model/ListMessagesResponse';
import ListMyGroupChannelsResponse from './model/ListMyGroupChannelsResponse';
import ListOpenChannelsResponse from './model/ListOpenChannelsResponse';
import ListOperatorsResponse from './model/ListOperatorsResponse';
import ListRegistrationOrDeviceTokensResponse from './model/ListRegistrationOrDeviceTokensResponse';
import ListUsersResponse from './model/ListUsersResponse';
import MarkAllMessagesAsReadRequest from './model/MarkAllMessagesAsReadRequest';
import MarkChannelMessagesAsReadRequest from './model/MarkChannelMessagesAsReadRequest';
import MigrateMessagesAdminMessageRequest from './model/MigrateMessagesAdminMessageRequest';
import MigrateMessagesFileMessageRequest from './model/MigrateMessagesFileMessageRequest';
import MigrateMessagesFileMessageRequestThumbnailsInner from './model/MigrateMessagesFileMessageRequestThumbnailsInner';
import MigrateMessagesRequest from './model/MigrateMessagesRequest';
import MigrateMessagesRequestMessagesInner from './model/MigrateMessagesRequestMessagesInner';
import MigrateMessagesTextMessageRequest from './model/MigrateMessagesTextMessageRequest';
import RegisterOperatorsToAGroupChannelRequest from './model/RegisterOperatorsToAGroupChannelRequest';
import RemoveARegistrationOrDeviceTokenResponse from './model/RemoveARegistrationOrDeviceTokenResponse';
import RemoveAllRegistrationOrDeviceTokenResponse from './model/RemoveAllRegistrationOrDeviceTokenResponse';
import ResetChatHistoryRequest from './model/ResetChatHistoryRequest';
import ResetChatHistoryResponse from './model/ResetChatHistoryResponse';
import ScheduleAnAnnouncementRequest from './model/ScheduleAnAnnouncementRequest';
import ScheduleAnAnnouncementRequestCreateChannelOptions from './model/ScheduleAnAnnouncementRequestCreateChannelOptions';
import ScheduleAnAnnouncementRequestMessage from './model/ScheduleAnAnnouncementRequestMessage';
import ScheduleAnAnnouncementResponse from './model/ScheduleAnAnnouncementResponse';
import ScheduleAnAnnouncementResponseMessage from './model/ScheduleAnAnnouncementResponseMessage';
import SendABotMessageRequest from './model/SendABotMessageRequest';
import SendAMessageRequest from './model/SendAMessageRequest';
import SendAdminMessageRequestBody from './model/SendAdminMessageRequestBody';
import SendFileMessageRequestBody from './model/SendFileMessageRequestBody';
import SendTextMessageRequestBody from './model/SendTextMessageRequestBody';
import SendTextMessageRequestBodyPushMessageTemplate from './model/SendTextMessageRequestBodyPushMessageTemplate';
import SendTextMessageRequestBodyPushMessageTemplateOneOf from './model/SendTextMessageRequestBodyPushMessageTemplateOneOf';
import SendbirdBasicUserInfo from './model/SendbirdBasicUserInfo';
import SendbirdDisappearingMessage from './model/SendbirdDisappearingMessage';
import SendbirdExtendedMessagePayload from './model/SendbirdExtendedMessagePayload';
import SendbirdFile from './model/SendbirdFile';
import SendbirdGroupChannel from './model/SendbirdGroupChannel';
import SendbirdGroupChannelDetail from './model/SendbirdGroupChannelDetail';
import SendbirdGroupChannelDetailChannel from './model/SendbirdGroupChannelDetailChannel';
import SendbirdMember from './model/SendbirdMember';
import SendbirdMessageResponse from './model/SendbirdMessageResponse';
import SendbirdMessageResponseMessageEvents from './model/SendbirdMessageResponseMessageEvents';
import SendbirdOpenChannel from './model/SendbirdOpenChannel';
import SendbirdParentMessageInfo from './model/SendbirdParentMessageInfo';
import SendbirdPushTriggerOption from './model/SendbirdPushTriggerOption';
import SendbirdReaction from './model/SendbirdReaction';
import SendbirdSmsFallback from './model/SendbirdSmsFallback';
import SendbirdSortedMetaarrayInner from './model/SendbirdSortedMetaarrayInner';
import SendbirdThumbnail from './model/SendbirdThumbnail';
import SendbirdUser from './model/SendbirdUser';
import StartTypingIndicatorsRequest from './model/StartTypingIndicatorsRequest';
import UpdateAChannelMetadataRequest from './model/UpdateAChannelMetadataRequest';
import UpdateAGroupChannelRequest from './model/UpdateAGroupChannelRequest';
import UpdateAMessageRequest from './model/UpdateAMessageRequest';
import UpdateAUserRequest from './model/UpdateAUserRequest';
import UpdateAnOpenChannelRequest from './model/UpdateAnOpenChannelRequest';
import UpdateChannelInvitationPreferenceRequest from './model/UpdateChannelInvitationPreferenceRequest';
import UpdateChannelInvitationPreferenceResponse from './model/UpdateChannelInvitationPreferenceResponse';
import UpdateCountPreferenceOfAChannelRequest from './model/UpdateCountPreferenceOfAChannelRequest';
import UpdateCountPreferenceOfChannelByUrlResponse from './model/UpdateCountPreferenceOfChannelByUrlResponse';
import UpdateExtraDataInAMessageRequest from './model/UpdateExtraDataInAMessageRequest';
import UpdateExtraDataInAMessageResponse from './model/UpdateExtraDataInAMessageResponse';
import UpdatePushPreferencesForAChannelRequest from './model/UpdatePushPreferencesForAChannelRequest';
import UpdatePushPreferencesForAChannelResponse from './model/UpdatePushPreferencesForAChannelResponse';
import UpdatePushPreferencesRequest from './model/UpdatePushPreferencesRequest';
import UpdatePushPreferencesResponse from './model/UpdatePushPreferencesResponse';
import UpdateSpecificUserMetadataRequest from './model/UpdateSpecificUserMetadataRequest';
import UpdateUserMetadataRequest from './model/UpdateUserMetadataRequest';
import ViewCountPreferenceOfAChannelResponse from './model/ViewCountPreferenceOfAChannelResponse';
import ViewNumberOfChannelsWithUnreadMessagesResponse from './model/ViewNumberOfChannelsWithUnreadMessagesResponse';
import ViewNumberOfDailyActiveUsersResponse from './model/ViewNumberOfDailyActiveUsersResponse';
import ViewNumberOfMonthlyActiveUsersResponse from './model/ViewNumberOfMonthlyActiveUsersResponse';
import ViewNumberOfUnreadMessagesResponse from './model/ViewNumberOfUnreadMessagesResponse';
import ViewPushPreferencesForAChannelResponse from './model/ViewPushPreferencesForAChannelResponse';
import ViewPushPreferencesResponse from './model/ViewPushPreferencesResponse';
import AnnouncementApi from './api/AnnouncementApi';
import BotApi from './api/BotApi';
import GroupChannelApi from './api/GroupChannelApi';
import MessageApi from './api/MessageApi';
import MetadataApi from './api/MetadataApi';
import ModerationApi from './api/ModerationApi';
import OpenChannelApi from './api/OpenChannelApi';
import StatisticsApi from './api/StatisticsApi';
import UserApi from './api/UserApi';


/**
* Server side JavaScript SDK for Sendbirds Platform API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SendbirdPlatformSdk = require('index'); // See note below*.
* var xxxSvc = new SendbirdPlatformSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SendbirdPlatformSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SendbirdPlatformSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SendbirdPlatformSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.1.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AcceptAnInvitationRequest model constructor.
     * @property {module:model/AcceptAnInvitationRequest}
     */
    AcceptAnInvitationRequest,

    /**
     * The AddARegistrationOrDeviceTokenRequest model constructor.
     * @property {module:model/AddARegistrationOrDeviceTokenRequest}
     */
    AddARegistrationOrDeviceTokenRequest,

    /**
     * The AddARegistrationOrDeviceTokenResponse model constructor.
     * @property {module:model/AddARegistrationOrDeviceTokenResponse}
     */
    AddARegistrationOrDeviceTokenResponse,

    /**
     * The AddExtraDataToAMessageRequest model constructor.
     * @property {module:model/AddExtraDataToAMessageRequest}
     */
    AddExtraDataToAMessageRequest,

    /**
     * The AddExtraDataToAMessageResponse model constructor.
     * @property {module:model/AddExtraDataToAMessageResponse}
     */
    AddExtraDataToAMessageResponse,

    /**
     * The BlockAUserRequest model constructor.
     * @property {module:model/BlockAUserRequest}
     */
    BlockAUserRequest,

    /**
     * The BlockAUserResponse model constructor.
     * @property {module:model/BlockAUserResponse}
     */
    BlockAUserResponse,

    /**
     * The CheckIfMemberResponse model constructor.
     * @property {module:model/CheckIfMemberResponse}
     */
    CheckIfMemberResponse,

    /**
     * The ChooseAPushNotificationContentTemplateRequest model constructor.
     * @property {module:model/ChooseAPushNotificationContentTemplateRequest}
     */
    ChooseAPushNotificationContentTemplateRequest,

    /**
     * The ChooseAPushNotificationContentTemplateResponse model constructor.
     * @property {module:model/ChooseAPushNotificationContentTemplateResponse}
     */
    ChooseAPushNotificationContentTemplateResponse,

    /**
     * The CreateABotRequest model constructor.
     * @property {module:model/CreateABotRequest}
     */
    CreateABotRequest,

    /**
     * The CreateABotResponse model constructor.
     * @property {module:model/CreateABotResponse}
     */
    CreateABotResponse,

    /**
     * The CreateABotResponseBot model constructor.
     * @property {module:model/CreateABotResponseBot}
     */
    CreateABotResponseBot,

    /**
     * The CreateABotResponseBotStyle model constructor.
     * @property {module:model/CreateABotResponseBotStyle}
     */
    CreateABotResponseBotStyle,

    /**
     * The CreateAChannelMetadataRequest model constructor.
     * @property {module:model/CreateAChannelMetadataRequest}
     */
    CreateAChannelMetadataRequest,

    /**
     * The CreateAChannelMetadataResponse model constructor.
     * @property {module:model/CreateAChannelMetadataResponse}
     */
    CreateAChannelMetadataResponse,

    /**
     * The CreateAGroupChannelRequest model constructor.
     * @property {module:model/CreateAGroupChannelRequest}
     */
    CreateAGroupChannelRequest,

    /**
     * The CreateAUserRequest model constructor.
     * @property {module:model/CreateAUserRequest}
     */
    CreateAUserRequest,

    /**
     * The CreateAnOpenChannelRequest model constructor.
     * @property {module:model/CreateAnOpenChannelRequest}
     */
    CreateAnOpenChannelRequest,

    /**
     * The CreateUserMetadataRequest model constructor.
     * @property {module:model/CreateUserMetadataRequest}
     */
    CreateUserMetadataRequest,

    /**
     * The CreateUserTokenRequest model constructor.
     * @property {module:model/CreateUserTokenRequest}
     */
    CreateUserTokenRequest,

    /**
     * The CreateUserTokenResponse model constructor.
     * @property {module:model/CreateUserTokenResponse}
     */
    CreateUserTokenResponse,

    /**
     * The FreezeAGroupChannelRequest model constructor.
     * @property {module:model/FreezeAGroupChannelRequest}
     */
    FreezeAGroupChannelRequest,

    /**
     * The FreezeAnOpenChannelRequest model constructor.
     * @property {module:model/FreezeAnOpenChannelRequest}
     */
    FreezeAnOpenChannelRequest,

    /**
     * The GetAGroupChannelResponse model constructor.
     * @property {module:model/GetAGroupChannelResponse}
     */
    GetAGroupChannelResponse,

    /**
     * The GetAGroupChannelResponseAllOf model constructor.
     * @property {module:model/GetAGroupChannelResponseAllOf}
     */
    GetAGroupChannelResponseAllOf,

    /**
     * The GetChannelInvitationPreferenceResponse model constructor.
     * @property {module:model/GetChannelInvitationPreferenceResponse}
     */
    GetChannelInvitationPreferenceResponse,

    /**
     * The GetTotalNumberOfMessagesInAChannelResponse model constructor.
     * @property {module:model/GetTotalNumberOfMessagesInAChannelResponse}
     */
    GetTotalNumberOfMessagesInAChannelResponse,

    /**
     * The GroupChannelListMembersResponse model constructor.
     * @property {module:model/GroupChannelListMembersResponse}
     */
    GroupChannelListMembersResponse,

    /**
     * The GroupChatListChannelsResponse model constructor.
     * @property {module:model/GroupChatListChannelsResponse}
     */
    GroupChatListChannelsResponse,

    /**
     * The HideAChannelRequest model constructor.
     * @property {module:model/HideAChannelRequest}
     */
    HideAChannelRequest,

    /**
     * The InviteAsMembersRequest model constructor.
     * @property {module:model/InviteAsMembersRequest}
     */
    InviteAsMembersRequest,

    /**
     * The InviteAsMembersResponse model constructor.
     * @property {module:model/InviteAsMembersResponse}
     */
    InviteAsMembersResponse,

    /**
     * The InviteAsMembersResponseAllOf model constructor.
     * @property {module:model/InviteAsMembersResponseAllOf}
     */
    InviteAsMembersResponseAllOf,

    /**
     * The JoinAChannelRequest model constructor.
     * @property {module:model/JoinAChannelRequest}
     */
    JoinAChannelRequest,

    /**
     * The JoinChannelsRequest model constructor.
     * @property {module:model/JoinChannelsRequest}
     */
    JoinChannelsRequest,

    /**
     * The LeaveAChannelRequest model constructor.
     * @property {module:model/LeaveAChannelRequest}
     */
    LeaveAChannelRequest,

    /**
     * The LeaveMyGroupChannelsRequest model constructor.
     * @property {module:model/LeaveMyGroupChannelsRequest}
     */
    LeaveMyGroupChannelsRequest,

    /**
     * The ListBlockedUsersResponse model constructor.
     * @property {module:model/ListBlockedUsersResponse}
     */
    ListBlockedUsersResponse,

    /**
     * The ListBotsResponse model constructor.
     * @property {module:model/ListBotsResponse}
     */
    ListBotsResponse,

    /**
     * The ListBotsResponseBotsInner model constructor.
     * @property {module:model/ListBotsResponseBotsInner}
     */
    ListBotsResponseBotsInner,

    /**
     * The ListBotsResponseBotsInnerAi model constructor.
     * @property {module:model/ListBotsResponseBotsInnerAi}
     */
    ListBotsResponseBotsInnerAi,

    /**
     * The ListBotsResponseBotsInnerBot model constructor.
     * @property {module:model/ListBotsResponseBotsInnerBot}
     */
    ListBotsResponseBotsInnerBot,

    /**
     * The ListBotsResponseBotsInnerBotStyle model constructor.
     * @property {module:model/ListBotsResponseBotsInnerBotStyle}
     */
    ListBotsResponseBotsInnerBotStyle,

    /**
     * The ListBotsResponseBotsInnerBotStyleColor model constructor.
     * @property {module:model/ListBotsResponseBotsInnerBotStyleColor}
     */
    ListBotsResponseBotsInnerBotStyleColor,

    /**
     * The ListBotsResponseBotsInnerFirstMessagesInner model constructor.
     * @property {module:model/ListBotsResponseBotsInnerFirstMessagesInner}
     */
    ListBotsResponseBotsInnerFirstMessagesInner,

    /**
     * The ListBotsResponseBotsInnerFirstMessagesInnerData model constructor.
     * @property {module:model/ListBotsResponseBotsInnerFirstMessagesInnerData}
     */
    ListBotsResponseBotsInnerFirstMessagesInnerData,

    /**
     * The ListBotsResponseBotsInnerSafeguard model constructor.
     * @property {module:model/ListBotsResponseBotsInnerSafeguard}
     */
    ListBotsResponseBotsInnerSafeguard,

    /**
     * The ListMessagesResponse model constructor.
     * @property {module:model/ListMessagesResponse}
     */
    ListMessagesResponse,

    /**
     * The ListMyGroupChannelsResponse model constructor.
     * @property {module:model/ListMyGroupChannelsResponse}
     */
    ListMyGroupChannelsResponse,

    /**
     * The ListOpenChannelsResponse model constructor.
     * @property {module:model/ListOpenChannelsResponse}
     */
    ListOpenChannelsResponse,

    /**
     * The ListOperatorsResponse model constructor.
     * @property {module:model/ListOperatorsResponse}
     */
    ListOperatorsResponse,

    /**
     * The ListRegistrationOrDeviceTokensResponse model constructor.
     * @property {module:model/ListRegistrationOrDeviceTokensResponse}
     */
    ListRegistrationOrDeviceTokensResponse,

    /**
     * The ListUsersResponse model constructor.
     * @property {module:model/ListUsersResponse}
     */
    ListUsersResponse,

    /**
     * The MarkAllMessagesAsReadRequest model constructor.
     * @property {module:model/MarkAllMessagesAsReadRequest}
     */
    MarkAllMessagesAsReadRequest,

    /**
     * The MarkChannelMessagesAsReadRequest model constructor.
     * @property {module:model/MarkChannelMessagesAsReadRequest}
     */
    MarkChannelMessagesAsReadRequest,

    /**
     * The MigrateMessagesAdminMessageRequest model constructor.
     * @property {module:model/MigrateMessagesAdminMessageRequest}
     */
    MigrateMessagesAdminMessageRequest,

    /**
     * The MigrateMessagesFileMessageRequest model constructor.
     * @property {module:model/MigrateMessagesFileMessageRequest}
     */
    MigrateMessagesFileMessageRequest,

    /**
     * The MigrateMessagesFileMessageRequestThumbnailsInner model constructor.
     * @property {module:model/MigrateMessagesFileMessageRequestThumbnailsInner}
     */
    MigrateMessagesFileMessageRequestThumbnailsInner,

    /**
     * The MigrateMessagesRequest model constructor.
     * @property {module:model/MigrateMessagesRequest}
     */
    MigrateMessagesRequest,

    /**
     * The MigrateMessagesRequestMessagesInner model constructor.
     * @property {module:model/MigrateMessagesRequestMessagesInner}
     */
    MigrateMessagesRequestMessagesInner,

    /**
     * The MigrateMessagesTextMessageRequest model constructor.
     * @property {module:model/MigrateMessagesTextMessageRequest}
     */
    MigrateMessagesTextMessageRequest,

    /**
     * The RegisterOperatorsToAGroupChannelRequest model constructor.
     * @property {module:model/RegisterOperatorsToAGroupChannelRequest}
     */
    RegisterOperatorsToAGroupChannelRequest,

    /**
     * The RemoveARegistrationOrDeviceTokenResponse model constructor.
     * @property {module:model/RemoveARegistrationOrDeviceTokenResponse}
     */
    RemoveARegistrationOrDeviceTokenResponse,

    /**
     * The RemoveAllRegistrationOrDeviceTokenResponse model constructor.
     * @property {module:model/RemoveAllRegistrationOrDeviceTokenResponse}
     */
    RemoveAllRegistrationOrDeviceTokenResponse,

    /**
     * The ResetChatHistoryRequest model constructor.
     * @property {module:model/ResetChatHistoryRequest}
     */
    ResetChatHistoryRequest,

    /**
     * The ResetChatHistoryResponse model constructor.
     * @property {module:model/ResetChatHistoryResponse}
     */
    ResetChatHistoryResponse,

    /**
     * The ScheduleAnAnnouncementRequest model constructor.
     * @property {module:model/ScheduleAnAnnouncementRequest}
     */
    ScheduleAnAnnouncementRequest,

    /**
     * The ScheduleAnAnnouncementRequestCreateChannelOptions model constructor.
     * @property {module:model/ScheduleAnAnnouncementRequestCreateChannelOptions}
     */
    ScheduleAnAnnouncementRequestCreateChannelOptions,

    /**
     * The ScheduleAnAnnouncementRequestMessage model constructor.
     * @property {module:model/ScheduleAnAnnouncementRequestMessage}
     */
    ScheduleAnAnnouncementRequestMessage,

    /**
     * The ScheduleAnAnnouncementResponse model constructor.
     * @property {module:model/ScheduleAnAnnouncementResponse}
     */
    ScheduleAnAnnouncementResponse,

    /**
     * The ScheduleAnAnnouncementResponseMessage model constructor.
     * @property {module:model/ScheduleAnAnnouncementResponseMessage}
     */
    ScheduleAnAnnouncementResponseMessage,

    /**
     * The SendABotMessageRequest model constructor.
     * @property {module:model/SendABotMessageRequest}
     */
    SendABotMessageRequest,

    /**
     * The SendAMessageRequest model constructor.
     * @property {module:model/SendAMessageRequest}
     */
    SendAMessageRequest,

    /**
     * The SendAdminMessageRequestBody model constructor.
     * @property {module:model/SendAdminMessageRequestBody}
     */
    SendAdminMessageRequestBody,

    /**
     * The SendFileMessageRequestBody model constructor.
     * @property {module:model/SendFileMessageRequestBody}
     */
    SendFileMessageRequestBody,

    /**
     * The SendTextMessageRequestBody model constructor.
     * @property {module:model/SendTextMessageRequestBody}
     */
    SendTextMessageRequestBody,

    /**
     * The SendTextMessageRequestBodyPushMessageTemplate model constructor.
     * @property {module:model/SendTextMessageRequestBodyPushMessageTemplate}
     */
    SendTextMessageRequestBodyPushMessageTemplate,

    /**
     * The SendTextMessageRequestBodyPushMessageTemplateOneOf model constructor.
     * @property {module:model/SendTextMessageRequestBodyPushMessageTemplateOneOf}
     */
    SendTextMessageRequestBodyPushMessageTemplateOneOf,

    /**
     * The SendbirdBasicUserInfo model constructor.
     * @property {module:model/SendbirdBasicUserInfo}
     */
    SendbirdBasicUserInfo,

    /**
     * The SendbirdDisappearingMessage model constructor.
     * @property {module:model/SendbirdDisappearingMessage}
     */
    SendbirdDisappearingMessage,

    /**
     * The SendbirdExtendedMessagePayload model constructor.
     * @property {module:model/SendbirdExtendedMessagePayload}
     */
    SendbirdExtendedMessagePayload,

    /**
     * The SendbirdFile model constructor.
     * @property {module:model/SendbirdFile}
     */
    SendbirdFile,

    /**
     * The SendbirdGroupChannel model constructor.
     * @property {module:model/SendbirdGroupChannel}
     */
    SendbirdGroupChannel,

    /**
     * The SendbirdGroupChannelDetail model constructor.
     * @property {module:model/SendbirdGroupChannelDetail}
     */
    SendbirdGroupChannelDetail,

    /**
     * The SendbirdGroupChannelDetailChannel model constructor.
     * @property {module:model/SendbirdGroupChannelDetailChannel}
     */
    SendbirdGroupChannelDetailChannel,

    /**
     * The SendbirdMember model constructor.
     * @property {module:model/SendbirdMember}
     */
    SendbirdMember,

    /**
     * The SendbirdMessageResponse model constructor.
     * @property {module:model/SendbirdMessageResponse}
     */
    SendbirdMessageResponse,

    /**
     * The SendbirdMessageResponseMessageEvents model constructor.
     * @property {module:model/SendbirdMessageResponseMessageEvents}
     */
    SendbirdMessageResponseMessageEvents,

    /**
     * The SendbirdOpenChannel model constructor.
     * @property {module:model/SendbirdOpenChannel}
     */
    SendbirdOpenChannel,

    /**
     * The SendbirdParentMessageInfo model constructor.
     * @property {module:model/SendbirdParentMessageInfo}
     */
    SendbirdParentMessageInfo,

    /**
     * The SendbirdPushTriggerOption model constructor.
     * @property {module:model/SendbirdPushTriggerOption}
     */
    SendbirdPushTriggerOption,

    /**
     * The SendbirdReaction model constructor.
     * @property {module:model/SendbirdReaction}
     */
    SendbirdReaction,

    /**
     * The SendbirdSmsFallback model constructor.
     * @property {module:model/SendbirdSmsFallback}
     */
    SendbirdSmsFallback,

    /**
     * The SendbirdSortedMetaarrayInner model constructor.
     * @property {module:model/SendbirdSortedMetaarrayInner}
     */
    SendbirdSortedMetaarrayInner,

    /**
     * The SendbirdThumbnail model constructor.
     * @property {module:model/SendbirdThumbnail}
     */
    SendbirdThumbnail,

    /**
     * The SendbirdUser model constructor.
     * @property {module:model/SendbirdUser}
     */
    SendbirdUser,

    /**
     * The StartTypingIndicatorsRequest model constructor.
     * @property {module:model/StartTypingIndicatorsRequest}
     */
    StartTypingIndicatorsRequest,

    /**
     * The UpdateAChannelMetadataRequest model constructor.
     * @property {module:model/UpdateAChannelMetadataRequest}
     */
    UpdateAChannelMetadataRequest,

    /**
     * The UpdateAGroupChannelRequest model constructor.
     * @property {module:model/UpdateAGroupChannelRequest}
     */
    UpdateAGroupChannelRequest,

    /**
     * The UpdateAMessageRequest model constructor.
     * @property {module:model/UpdateAMessageRequest}
     */
    UpdateAMessageRequest,

    /**
     * The UpdateAUserRequest model constructor.
     * @property {module:model/UpdateAUserRequest}
     */
    UpdateAUserRequest,

    /**
     * The UpdateAnOpenChannelRequest model constructor.
     * @property {module:model/UpdateAnOpenChannelRequest}
     */
    UpdateAnOpenChannelRequest,

    /**
     * The UpdateChannelInvitationPreferenceRequest model constructor.
     * @property {module:model/UpdateChannelInvitationPreferenceRequest}
     */
    UpdateChannelInvitationPreferenceRequest,

    /**
     * The UpdateChannelInvitationPreferenceResponse model constructor.
     * @property {module:model/UpdateChannelInvitationPreferenceResponse}
     */
    UpdateChannelInvitationPreferenceResponse,

    /**
     * The UpdateCountPreferenceOfAChannelRequest model constructor.
     * @property {module:model/UpdateCountPreferenceOfAChannelRequest}
     */
    UpdateCountPreferenceOfAChannelRequest,

    /**
     * The UpdateCountPreferenceOfChannelByUrlResponse model constructor.
     * @property {module:model/UpdateCountPreferenceOfChannelByUrlResponse}
     */
    UpdateCountPreferenceOfChannelByUrlResponse,

    /**
     * The UpdateExtraDataInAMessageRequest model constructor.
     * @property {module:model/UpdateExtraDataInAMessageRequest}
     */
    UpdateExtraDataInAMessageRequest,

    /**
     * The UpdateExtraDataInAMessageResponse model constructor.
     * @property {module:model/UpdateExtraDataInAMessageResponse}
     */
    UpdateExtraDataInAMessageResponse,

    /**
     * The UpdatePushPreferencesForAChannelRequest model constructor.
     * @property {module:model/UpdatePushPreferencesForAChannelRequest}
     */
    UpdatePushPreferencesForAChannelRequest,

    /**
     * The UpdatePushPreferencesForAChannelResponse model constructor.
     * @property {module:model/UpdatePushPreferencesForAChannelResponse}
     */
    UpdatePushPreferencesForAChannelResponse,

    /**
     * The UpdatePushPreferencesRequest model constructor.
     * @property {module:model/UpdatePushPreferencesRequest}
     */
    UpdatePushPreferencesRequest,

    /**
     * The UpdatePushPreferencesResponse model constructor.
     * @property {module:model/UpdatePushPreferencesResponse}
     */
    UpdatePushPreferencesResponse,

    /**
     * The UpdateSpecificUserMetadataRequest model constructor.
     * @property {module:model/UpdateSpecificUserMetadataRequest}
     */
    UpdateSpecificUserMetadataRequest,

    /**
     * The UpdateUserMetadataRequest model constructor.
     * @property {module:model/UpdateUserMetadataRequest}
     */
    UpdateUserMetadataRequest,

    /**
     * The ViewCountPreferenceOfAChannelResponse model constructor.
     * @property {module:model/ViewCountPreferenceOfAChannelResponse}
     */
    ViewCountPreferenceOfAChannelResponse,

    /**
     * The ViewNumberOfChannelsWithUnreadMessagesResponse model constructor.
     * @property {module:model/ViewNumberOfChannelsWithUnreadMessagesResponse}
     */
    ViewNumberOfChannelsWithUnreadMessagesResponse,

    /**
     * The ViewNumberOfDailyActiveUsersResponse model constructor.
     * @property {module:model/ViewNumberOfDailyActiveUsersResponse}
     */
    ViewNumberOfDailyActiveUsersResponse,

    /**
     * The ViewNumberOfMonthlyActiveUsersResponse model constructor.
     * @property {module:model/ViewNumberOfMonthlyActiveUsersResponse}
     */
    ViewNumberOfMonthlyActiveUsersResponse,

    /**
     * The ViewNumberOfUnreadMessagesResponse model constructor.
     * @property {module:model/ViewNumberOfUnreadMessagesResponse}
     */
    ViewNumberOfUnreadMessagesResponse,

    /**
     * The ViewPushPreferencesForAChannelResponse model constructor.
     * @property {module:model/ViewPushPreferencesForAChannelResponse}
     */
    ViewPushPreferencesForAChannelResponse,

    /**
     * The ViewPushPreferencesResponse model constructor.
     * @property {module:model/ViewPushPreferencesResponse}
     */
    ViewPushPreferencesResponse,

    /**
    * The AnnouncementApi service constructor.
    * @property {module:api/AnnouncementApi}
    */
    AnnouncementApi,

    /**
    * The BotApi service constructor.
    * @property {module:api/BotApi}
    */
    BotApi,

    /**
    * The GroupChannelApi service constructor.
    * @property {module:api/GroupChannelApi}
    */
    GroupChannelApi,

    /**
    * The MessageApi service constructor.
    * @property {module:api/MessageApi}
    */
    MessageApi,

    /**
    * The MetadataApi service constructor.
    * @property {module:api/MetadataApi}
    */
    MetadataApi,

    /**
    * The ModerationApi service constructor.
    * @property {module:api/ModerationApi}
    */
    ModerationApi,

    /**
    * The OpenChannelApi service constructor.
    * @property {module:api/OpenChannelApi}
    */
    OpenChannelApi,

    /**
    * The StatisticsApi service constructor.
    * @property {module:api/StatisticsApi}
    */
    StatisticsApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
